### ISSUE TITLE
Make Slack channels configurable

### ISSUE THREAD

**Issue by nikita-v** [keel-hq/keel#113]
Hi!
It may be useful to configure Slack channels (for approvals and notifications) for each deployment.

**Comment by ipadavic** [comment]
Hi, 
I is there any way we can change approvals notifications to go to some other channel and not general? 

Notifications for gcr new images are working fine with defined channel in deployment but approvals are coming to general channel

**Comment by rusenask** [comment]
Hello, at the moment it's not configurable. Would you prefer to use the same channel as notifications or a separate channel for approvals?

**Comment by ipadavic** [comment]
For our use case, same channel is fine. Btw keel is great. It's missing some features but heading in right direction 👍

**Comment by rajasaur** [comment]
In my case, I think a separate channel would be nice but also the ability (optional) to have only select people approve would be great. The workaround is to do it in a private channel where only selected people are invited, so its not that big a problem.

But it would be nice to get a audit of who approved the releases (the usernames in slack).
