### ISSUE TITLE
Docker credentials were not found among secrets

### ISSUE THREAD

**Issue by vonglasow** [keel-hq/keel#117]
Hello, I can pull images from my privates registry, but keel (v0.47) can't connect on it. The error raised is `time="2017-11-28T17:35:44Z" level=warning msg="secrets.defaultGetter.lookupSecrets: docker credentials were not found among secrets" image=private.registry.com/myproject/example namespace=dev provider=kubernetes registry=private.registry.com secrets="[private-registry]"` My secrets `.dockercfg` looks like
```
{
    "gcr.myproject.com": {
        "auth": "base64sddfsdf"
    },
    "ucr.myproject.io": {
        "auth": "base64sfdsdf"
    }
}
```
The release 0.43 explain we should use secrets created from `kubectl create secret docker-registry myregistrykey --docker-server=https://index.docker.io/v1/ --docker-username=<user> --docker-password=<pass> --docker-email=<email>` so it should looks like

```
{"https://index.docker.io/v1/":{"username":"user","password":"pass","email":"email","auth":"dXNlcjpwYXNz"}}
```
And in the code https://github.com/keel-hq/keel/blob/master/secrets/secrets.go#L213-L226 we can see it's possible to extract credentials from `auth`. So, is it mandatory to have username and password in secret dockercfg to allow keel to contact the registry for a poll or is it my dockercfg format which is the problem ?

Here the answer on slack:

> karolis [12:28 PM] 
> Hello, there are several (I think 3) ways credentials can be stored for registries
> currently it can either work with username/password or base 64 encoded auth
> if you could create an issue with an example command on how you are creating secret I could then try to reproduce it
> your dockercfg should work :neutral_face:

You can found everything to reproduce the case on this gist.
https://gist.github.com/vonglasow/efcf09821b6d86b1c0b85bbbbc695476

**Comment by rusenask** [comment]
Hi, what is in the ```"auth": "base64sfdsdf"``` ? is it encoded `username:password` or something else?

**Comment by vonglasow** [comment]
@rusenask yes it's encoded `username:password`, I will try `0.5.0` tomorrow thanks for your answer

**Comment by vonglasow** [comment]
@rusenask I was too curious to wait your latest version `0.5.0-rc.1` works thanks for your help.
