### ISSUE TITLE
400 Errors talking to gcr.io

### ISSUE THREAD

**Issue by rajasaur** [keel-hq/keel#118]
Im a newbie trying out Keel, so it could be something that Ive done, but havent been able to find what it is after looking at all the documentation available.

I have a GKE cluste running 1.7.8 and Ive setup Keel as mentioned in the install guide. On one of my deployments which has the image hosted on gcr.io on the same project, I set up
```
  keel.sh/policy: major
  keel.sh/trigger: poll
```
to see if Polling would work. Once the setup was run and doing a kubectl log -f <keel-pod> -n kube-system, I get the following statements repeated.

```
time="2017-12-02T08:42:29Z" level=error msg="trigger.poll.RepositoryWatcher.addJob: failed to get image digest" error="Head https://gcr.io/v2/upheld-flow-183107/php/manifests/5.0.0: http: non-successful response (status=400 body=\"\")" image="gcr.io/upheld-flow-183107/php:5.0.0"
time="2017-12-02T08:42:29Z" level=error msg="trigger.poll.RepositoryWatcher.Watch: failed to add image watch job" error="Head https://gcr.io/v2/upheld-flow-183107/php/manifests/5.0.0: http: non-successful response (status=400 body=\"\")" image_name="gcr.io/upheld-flow-183107/php:5.0.0" registry_username=
time="2017-12-02T08:42:29Z" level=error msg="trigger.poll.manager: failed to start watching repository" error="Head https://gcr.io/v2/upheld-flow-183107/php/manifests/5.0.0: http: non-successful response (status=400 body=\"\")" image="gcr.io/upheld-flow-183107/php:5.0.0" schedule="@every 1m"
```

It looks like its trying to authenticate but its failing but Im not able to see how to setup access for it (if its required). 

My original deployment is running well, but I was expecting a postive log about being able to inform the deployment to slack notifier, but I have the above repeating every minute (default polling interval)

Can someone point as to what is wrong in this setup?

Environment:
Keel : 0.4.7
GKE running 1.7.8-gke.0

**Comment by rusenask** [comment]
Hello, I have actually never tried authentication with the GCR as there is no need to use polling but I guess there are some nuances. With GCR the best option is to use pubsub (you could also configure pubsub to use webhooks and point them to keel). 

If google creates a dockercfg file for GCR registries then Keel could probably use that, although since you don't need to configure secrets, it will never look into that file.

**Comment by rajasaur** [comment]
Thanks, Tried with pubsub and works very well. Ill close this for now.
