### ISSUE TITLE
Record the version change when updating deployment

### ISSUE THREAD

**Issue by rajasaur** [keel-hq/keel#119]
When we create a deployment with
kubectl create -f <file.yaml> --record
it records the deployment history, which shows up when we do a 
kubectl rollout history deployments/my-deployment

Right now, with Keel, it seems to update the same command everytime the revision gets bumped. for e.g. in my case, I started with image revision 1.0.0 , updated to 1.0.1, which updated my deployment but on displaying the rollout history, it shows like
```
emerald-2:k8s raja$ kubectl rollout history deployment/apache-deployment
deployments "apache-deployment"
REVISION	CHANGE-CAUSE
1		kubectl create --filename=httpd/nginx-deployment.yaml --record=true
2		kubectl create --filename=httpd/nginx-deployment.yaml --record=true
```

It looks like my original command has been repeated for the second revision. But if you look at https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#checking-rollout-history-of-a-deployment, it looks like when you can set the image using the "set image" command (Not sure what keel uses), it records it accordingly. This helps when doing rollbacks so we know the history when rolling back.

Would it be possible to do this so that the history becomes more clearer when using "rollout history"

**Comment by rusenask** [comment]
Keel uses k8s API for deployment update. Currently updated deployments result in a number of revisions (I think default is 200) but probably slightly different. 

Aiming for similar functionality sounds good. I wonder whether this is available on the API or is it a kubectl feature.

**Comment by praseodym** [comment]
Looks like this uses the `kubernetes.io/change-cause=` annotation so it should be fairly simple to use through the API.

**Comment by rusenask** [comment]
would we want to see something like:

```
emerald-2:k8s raja$ kubectl rollout history deployment/apache-deployment
deployments "apache-deployment"
REVISION	CHANGE-CAUSE
1		keel automated update version 0.5.6 -> 0.6.0 
2		keel automated update version 0.6.0 -> 0.7.0 
```

?

**Comment by praseodym** [comment]
Yes!

**Comment by rusenask** [comment]
Added in `0.8.0`, thanks for pointing to that `kubernetes.io/change-cause=`, didn't think it's that simple! :)
