### ISSUE TITLE
update helm chart of keel

### ISSUE THREAD

**Issue by alexanderreinelt** [keel-hq/keel#134]
Hi, one of our developers contributed to this project and made it possible to send notifications and approvals via hipchat. I'm currently working on a helm chart for keel to use these features.
If there is some interest I could contribute it to this project as well.

**Comment by rusenask** [comment]
Hi Alexander, it would be great. If you could send a PR with the updated
helm chart here, I could update kubeapps repo as well as it's a bit overdue
already.

**Comment by alexanderreinelt** [comment]
Okay, when I'm done with that I will contribute that in a fork here. Hopefully I will make it work in the next days.

**Comment by rusenask** [comment]
Thank you for your contribution.
