### ISSUE TITLE
Sync up keel chart with upstream

### ISSUE THREAD

**Issue by rimusz** [keel-hq/keel#136]
Sync up keel chart changes with Helm upstream

**Comment by rusenask** [comment]
Do you think it would make sense to put Keel into a separate namespace? I can't remember what was historical reason for it to be in `kube-system`. With RBAC now it should work from anywhere.

**Comment by rimusz** [comment]
yup, we should use `keel` namespace

**Comment by rusenask** [comment]
I can do it in https://github.com/keel-hq/keel/pull/137

**Comment by rimusz** [comment]
let me check the difference we have between charts and update it first here, then open PR upstream
