### ISSUE TITLE
Slack token

### ISSUE THREAD

**Issue by marccardinal** [keel-hq/keel#139]
Good evening,

Keel is giving me this error:

```time="2018-01-12T03:45:18Z" level=error msg="extension.notification.slack: failed to send notification" channel=alerts error=channel_not_found```

I gave it this config:

```
            - name: SLACK_TOKEN
              value: xoxb-super-secret-token-here
            - name: SLACK_CHANNELS
              value: alerts
            - name: SLACK_APPROVALS_CHANNEL
              value: alerts
```

The slack channel exists and the token came from a bot user token created using https://my.slack.com/services/new/bot linked from this page: https://api.slack.com/custom-integrations/bot-users and I called it keel.

Is that the right kind of token?

**Comment by rusenask** [comment]
Hi, try inviting bot to that channel via slack. Token should be okay as you would probably see authentication errors otherwise.

**Comment by marccardinal** [comment]
Ah! That did the trick, thanks a lot!
