### ISSUE TITLE
Specific Slack channel notification per deployment

### ISSUE THREAD

**Issue by skamoen** [keel-hq/keel#142]
Basically as described in #113, however that ticket was closed with only a separate approval feature.

I'd like to set channels for each deployment so that deployments for `application-a` sends notifications to a specific slack channel, and `application-b` to another.

**Comment by rusenask** [comment]
Hi, sorry for closing that issue without completely resolving it. 

It's a good idea to have an ability to override default channels by labels or annotations. I wonder what to do about Helm though, would this be configurable at chart or somewhere else. Nevertheless we could add labels or annotations to the event:

```Golang
type EventNotification struct {
	Name      string       `json:"name"`
	Message   string       `json:"message"`
	CreatedAt time.Time    `json:"createdAt"`
	Type      Notification `json:"type"`
	Level     Level        `json:"level"`
        Labels map[string]string
}
```
And overwrite more than one thing.

**Comment by rusenask** [comment]
@skamoen  added this in https://github.com/keel-hq/keel/pull/146, docs: https://keel.sh/v1/guide/documentation.html#Overriding-default-channels-per-deployment. Could you try it out and see whether this is something that you wanted?

**Comment by skamoen** [comment]
Yes. This is perfect. Thanks a lot!
