### ISSUE TITLE
Supplying google application credentials via --set breaks on template render 

### ISSUE THREAD

**Issue by jasonjho** [keel-hq/keel#148]
Supplying Google service account keys as a helm value:

`helm upgrade --install ... --set googleApplicationCredentials=$(cat /path/to/jsonkey)`

will produce the following error: 

```Error: render error in "keel/templates/secrets-google.yaml": template: keel/templates/secrets-google.yaml:14:81: executing "keel/templates/secrets-google.yaml" at <b64enc>: wrong type for value; expected string; got []interface {}```

Due to the way Helm/Go processes JSON values from `--set`, the current workaround is to remove the `b64enc` call (https://github.com/keel-hq/keel/blob/master/chart/keel/templates/secrets-google.yaml#L14) and perform the base64 encoding prior to assigning the variable.

---
The fix:

`helm upgrade --install ... --set googleApplicationCredentials=$(cat /path/to/jsonkey | base64)`

**Comment by rimusz** [comment]
fix in #149

**Comment by rusenask** [comment]
Thanks guys for finding and fixing this :)
