### ISSUE TITLE
slack setup

### ISSUE THREAD

**Issue by hexsprite** [keel-hq/keel#165]
Hi, first off thanks for this great project!

I'm trying to configure the slack notifications for deployments. I setup the SLACK_TOKEN environment variable to what Slack is calling a "legacy token".

I set the SLACK_CHANNELS variable to `dev-notifications`.

When I try to start keel I get this error:

```
time="2018-03-18T21:41:21Z" level=fatal msg="main: failed to setup slack bot\n" error="could not find bot in the list of names, check if the bot is called \"keel\" "
```

I checked the docs but didn't see any additional setup steps. Should I just setup a fake user called `keel`?

**Comment by rusenask** [comment]
Hi! 
No, when adding a "custom integration" -> "bot", set a name to "keel":

![screen shot 2018-03-18 at 23 36 05](https://user-images.githubusercontent.com/9080105/37572606-7398f8cc-2b05-11e8-99d5-6696e4c47ab2.png)

![screen shot 2018-03-18 at 23 33 22](https://user-images.githubusercontent.com/9080105/37572575-1abbb730-2b05-11e8-9772-83496d1ed344.png)

You might also want to then invite Keel into that slack channel if you are planning to use approvals (it needs to see the messages). 

I hope it helps :)

**Comment by hexsprite** [comment]
OK thanks there's so many ways to integrate with Slack I got a bit confused. Seems to work now.

**Comment by rusenask** [comment]
Great :) I guess it would make sense to add these steps to the docs. Just not sure how long it will take till Slack changes the interface.

**Comment by hexsprite** [comment]
sounds like it would be a good improvement i'm sure someone else will open an issue when it becomes a problem :)

**Comment by rusenask** [comment]
moved https://github.com/keel-hq/keel/issues/186
