### ISSUE TITLE
AWS ECR does not conform to v2 registry spec and therefore returns an 'invalid checksum' error

### ISSUE THREAD

**Issue by cparedes** [keel-hq/keel#173]
AWS ECR does not return a `Docker-Content-Digest` header and therefore doesn't conform to v2 API spec.

We could modify this to look elsewhere for digest info: https://github.com/rusenask/docker-registry-client/blob/bf1d91b397917b39e5f0478dd679c8aa224ca91e/registry/manifest.go#L92, but I'm not a huge fan of that option.

Same thing for https://github.com/keel-hq/keel/blob/ea8d5f2bb3e1c82df34c3bb3398092d88102fafd/registry/registry.go#L102

v1 API doesn't seem to work at all on ECR either.

What do folks think?

**Comment by cparedes** [comment]
This should fix the issue, but still need to test: https://github.com/rusenask/docker-registry-client/pull/1

**Comment by rusenask** [comment]
fixed in https://github.com/keel-hq/keel/releases/tag/0.8.3
