### ISSUE TITLE
force ignores rolling deployment settings

### ISSUE THREAD

**Issue by hexsprite** [keel-hq/keel#177]
I just did a deployment and was surprised that my rolling deployment settings were ignored.

While reviewing the logs I can see that it appears that the force option achieves it's result but manually deleting the pods in question.

If so this is not compatible with a rolling deployment it may be worth documenting as it's not that useful for production in that case.

How to force a pull across a deployment seems to be a larger issue in k8s in general:
- https://stackoverflow.com/questions/40366192/kubernetes-how-to-make-deployment-to-update-image/40368520#40368520
- https://github.com/kubernetes/kubernetes/issues/13488#issuecomment-375316996

**Comment by rusenask** [comment]
Hi, yes, unfortunately there are some downsides when not using version tags for images. These workarounds mentioned in comments only work for some time but there is no guarantee that they will work one month from now :) 

Previously Keel was renaming image to force kubernetes to pull a new image but that behaviour was changed in some later k8s version and therefore force updates stopped working. The only robust strategy in this case seems to be pod deletion and it's used by a number of companies. We could introduce a configurable delay between deletions or maybe even a check that would delete pod one at a time (more complicated). 

How many replicas do you run in your deployment?

**Comment by hexsprite** [comment]
Currently my deployments are using 2 replicas.

**Comment by rusenask** [comment]
maybe a configurable delay between killing pods could do the job?

**Comment by hexsprite** [comment]
yes having a configurable delay between killing pods would be a good workaround for now.

i was trying to dream up an ideal workflow. I don't really want to use semver as it's not really relevant to my workflow. ideally it would use the native k8s rolling deploy functionality.

one thought I had was what if one could treat a docker tag kind of like a branch... you'd look for an update to the docker image under that tag name... but then you do a lookup of it's git sha-tagged name to use for rolling deploy.

For example I might have this config:

```
...
  labels:
    keel.sh/policy: force  # maybe a different policy...
    keel.sh/trigger: pullSource
    keel.sh/sourceImage: my/app:stable
```

Now when a new image is pulled for `my/app:stable` it will try to find a new image with the same SHA. In this case it might find `my/app:44c040286e6e41d9eabbd03e4abc65d00bcbf0af` and then use that to do the rolling deploy.

The `sourceImage` attribute lets you keep watching the right tag even though a different tag is deployed. Anyway.. blue sky thinking ;)

**Comment by rusenask** [comment]
Closing this, if terminate delay won't help, we can think of something else.

**Comment by hexsprite** [comment]
Thanks it’s working well
