### ISSUE TITLE
Private repo poll trigger silently doesn't trigger.

### ISSUE THREAD

**Issue by Antiarchitect** [keel-hq/keel#180]
I have Kubernetes provider set up with one public and two private repos from cloud.docker.com. And if public one has been triggered normally, privates are staying silent. @rusenask supposed the thing can be in parsing imagePullSecrets secret. So here it is:
```
Name:         cloud-docker-com-secret
Namespace:    default
Labels:       app=not-matter-at-all
             chart=not-matter-either-0.1.0
             heritage=Tiller
             release=not-matter-release
Annotations:  <none>

Type:  kubernetes.io/dockerconfigjson

Data
====
.dockerconfigjson:  206 bytes
```
Here is cleaned out dockerconfigjson:
```
{"auths":{"https://index.docker.io/v1/":{"username":"login","password":"somepass","email":"email@email.com","auth":"longbase64secret"}}}
```
Keel version: 0.8.4
Kubernetes: 1.9.3

**Comment by Antiarchitect** [comment]
I just looked at the code (I'm golang noob), and here: https://github.com/keel-hq/keel/blob/master/secrets/secrets.go#L173 keel tries to unmarshal JSON, but the .dockerconfigjson field in Secret of this type seems entirely encoded with base64. I could be wrong and on keel level, it is cleaned out already.

**Comment by rusenask** [comment]
Hi, I have been looking at secrets package in Keel, tried adding unit tests with your config but I suspect that it has something to do with your deployment.

Are you using Helm? Keel uses selectors to find secrets that belong to this chart. Selector code is here: https://github.com/keel-hq/keel/blob/master/provider/helm/helm.go#L190, example chart repo: https://github.com/webhookrelay/webhook-demo/blob/master/webhookdemo/templates/deployment.yaml (those labels with `app` and `release` should be generated by default when creating new chart template)

**Comment by Antiarchitect** [comment]
Have needed labels, but use 
```
     app: {{ template "adara-cryptonodes-helm.fullname" . }}
```
Is this OK?

**Comment by rusenask** [comment]
Hi, sorry, had a long weekend :) it just needs them to be unique and to be able to find the pods created by that helm chart.

Since secret ref is available only through the pods, it needs:
1. get unique identifier from the chart that
2. use that identifier to get the pods
3. check secret ref from pods to use for registry login

this way you don't need to setup credentials for Keel to query docker registries. 
Hope that helps!
