### ISSUE TITLE
Staging/acceptance/prod & versionning

### ISSUE THREAD

**Issue by azr** [keel-hq/keel#182]
Hi there,

I have a staging/acceptance/production setup.
I would like to be able to update all of their deploys independently depending on when I push to  feature branch/master branch/tag respectively.

But I have to ask what would work and may be it would be nice if this would be documented somewhere.

Here's a few ideas:

1. Differenciating with special tag ( or pre-release tag ) ?

staging deploy : `docker.com/this/that:latest-staging`

acc : `docker.com/this/that:latest-acceptance`

prod `docker.com/this/that:latest`

if I do this with a force `force` setting for all deploys, will a docker push to `image.com:latest-staging`  also trigger a deploy for my prod deployment ?

2. Differenciating with image name ?

staging deploy : `docker.com/this/that-staging:latest`

acc : `docker.com/this/that-acceptance:latest`

prod `docker.com/this/that:latest`

I kinda don't like this ? But is this the only working solution now ? If yes may be I will try to have solution 1 work by doing a P.R. if you agree :)

**Comment by azr** [comment]
Here's another setting I though of:

 3. Differenciating with special tag + version ( or pre-release tag ) ?

staging deploy : `docker.com/this/that:v2.3.4-staging`

acc : `docker.com/this/that:v2.3.4-acceptance`

prod `docker.com/this/that:v2.3.4`

if I do this with a `major` setting for all deploys, will a docker push to `image.com:v2.3.5-acceptance`  trigger a deploy for my acceptance deployment ?

**Comment by rusenask** [comment]
Hi,
Option 1 would work if you are using polling trigger,
deployments with `docker.com/this/that:latest-acceptance` would only watch digest of `docker.com/this/that:latest-acceptance` tag and once it's changed, update it. 

Option 2 would work with any trigger.

Ideally I would want to have option 3 as semver allows metadata inside version tags. It's related to https://github.com/keel-hq/keel/issues/63 but we never nailed it down completely. 

Maybe we could have additional annotation to inform keel that metadata parts should match?
that `v2.3.4-acceptance` should only update deployments with `v2.3.4-acceptance` and so on. What do you think?

**Comment by azr** [comment]
Could we get this from the context, from the used tag ?
When image tag is 
`docker.com/this/that:v2.3.4-staging` specifically then we only match on `docker.com/this/that:v[...]-staging`

**Comment by azr** [comment]
Will check #63
