### ISSUE TITLE
AWS ECR Polling on AWS EC2 with kops

### ISSUE THREAD

**Issue by MOZGIII** [keel-hq/keel#193]
I have a Kubernetes setup on AWS EC2 with kops. I deploy images that are stored on AWS ECR in the same account.

Polling fails with the following logs:
```
time="2018-04-18T08:50:10Z" level=error msg="trigger.poll.RepositoryWatcher.addJob: failed to get image digest" error="Get https://123.dkr.ecr.us-east-2.amazonaws.com/v2/image1/manifests/tag: http: non-successful response (status=401 body=\"Not Authorized\\n\")" image="123.dkr.ecr.us-east-2.amazonaws.com/image1:tag"
time="2018-04-18T08:50:10Z" level=error msg="trigger.poll.RepositoryWatcher.Watch: failed to add image watch job" error="Get https://123.dkr.ecr.us-east-2.amazonaws.com/v2/image1/manifests/tag: http: non-successful response (status=401 body=\"Not Authorized\\n\")" image_name="123.dkr.ecr.us-east-2.amazonaws.com/image1:tag" registry_username=
time="2018-04-18T08:50:10Z" level=error msg="trigger.poll.manager: failed to start watching repository" error="Get https://123.dkr.ecr.us-east-2.amazonaws.com/v2/image1/manifests/tag: http: non-successful response (status=401 body=\"Not Authorized\\n\")" image="123.dkr.ecr.us-east-2.amazonaws.com/image1:tag" schedule="@every 1m"
time="2018-04-18T08:50:10Z" level=error msg="trigger.poll.RepositoryWatcher.addJob: failed to get image digest" error="Get https://123.dkr.ecr.us-east-2.amazonaws.com/v2/image2/manifests/tag: http: non-successful response (status=401 body=\"Not Authorized\\n\")" image="123.dkr.ecr.us-east-2.amazonaws.com/image2:tag"
time="2018-04-18T08:50:10Z" level=error msg="trigger.poll.RepositoryWatcher.Watch: failed to add image watch job" error="Get https://123.dkr.ecr.us-east-2.amazonaws.com/v2/image2/manifests/tag: http: non-successful response (status=401 body=\"Not Authorized\\n\")" image_name="123.dkr.ecr.us-east-2.amazonaws.com/image2:tag" registry_username=
time="2018-04-18T08:50:10Z" level=error msg="trigger.poll.manager: failed to start watching repository" error="Get https://123.dkr.ecr.us-east-2.amazonaws.com/v2/image2/manifests/tag: http: non-successful response (status=401 body=\"Not Authorized\\n\")" image="123.dkr.ecr.us-east-2.amazonaws.com/image2:tag" schedule="@every 1m"
```

Normally pulling images works without any additional configuration (i.e. when creating a pod), but keel seem to have issues with ECR. How can I resolve this?

**Comment by rusenask** [comment]
Hi, do you use deployment.yml or helm chart to deploy your app?

**Comment by MOZGIII** [comment]
I use `deployment.yml`

**Comment by MOZGIII** [comment]
Precisely `kubectl apply -f ...` deploys a bunch of apps (~15 currently). keel is deployed using `kubectl apply -f ...` as well (without helm).
Kubernetes version:
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:26:04Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by rusenask** [comment]
It seems that it doesn't find secrets for the registry. How do you create a service account to pull images?

**Comment by MOZGIII** [comment]
Take a look in here: https://docs.aws.amazon.com/sdk-for-go/api/service/ecr/#ECR.GetAuthorizationToken
and here: https://docs.aws.amazon.com/AmazonECR/latest/APIReference/API_GetAuthorizationToken.html
and also here: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html

It should be fairly easy to add support for authenticating via AWS using the Go AWS API (first link).
Two other links are just implementation details of how the API works and how would AWS authorize access to it's API when using EC2 instance role.

**Comment by MOZGIII** [comment]
Better option, of course, would be to somehow rely on kubernetes itself to do the polling... Maybe interacting with kubelets...

**Comment by rusenask** [comment]
what's interesting here is that someone already used it successfully with ECR, I wonder whether something changed in how they do auth or maybe there are some tricks to make it work. I will investigate. 

Since kubernetes sets ImagePullSecrets for all the pods, Keel just extracts them and reuses for registry auth, therefore user doesn't have to supply any additional authentication. Clearly with ECR something else is happening :) Go AWS client seems like a good solution if we cannot rely on pod secrets.

**Comment by MOZGIII** [comment]
Just checked - there are no secrets in the pods at my instance.
This is kind of blocking for me. Will you be able to look into it this week?

**Comment by rusenask** [comment]
Yes, will finish current outstanding PR and then get this sorted.

**Comment by MOZGIII** [comment]
Great, thanks a lot

**Comment by rusenask** [comment]
Actually, if we go that route it would be even better to use ECR events from the message bus, instant updates like with google's GCR would be great :)

**Comment by MOZGIII** [comment]
Though, maybe a good idea would be to split those into different tasks - I'm going to stick with polling because it should take less configuration and that's important for my current use case.
Definitely, full ECR events would be useful for keel, however it seem to be a trickier thing than just adding proper polling support for ECR.

**Comment by rusenask** [comment]
Hi, just an update. Still stuck a bit with tests for k8s provider on current PR. Will probably only have time for this during the weekend.

**Comment by MOZGIII** [comment]
Any updates?

**Comment by rusenask** [comment]
I am working on a separate branch. I had a look at how kubernetes is doing this but it's too overcomplicated for our use case. 

Currently I think user will have to set several environment variables for authentication (AWS_ACCESS_KEY_ID, AWS_ACCESS_KEY).

**Comment by MOZGIII** [comment]
Do you think it would work if I just set those for the keel container in deployment (not for all the deployments that keel has to look after in k8s)?

**Comment by rusenask** [comment]
Yes, that would only be needed for Keel.

**Comment by MOZGIII** [comment]
Great, I'll try that

**Comment by MOZGIII** [comment]
I guess I misunderstood and what you mentioned is the behavior that'd be available after you merge your branch.
Can I take a loot btw?

**Comment by rusenask** [comment]
It's not merged, still work in progress. I never used ECR and didn't have AWS account so I have to set it up as well for testing :) https://github.com/keel-hq/keel/compare/feature/ecr_registry_auth?expand=1

**Comment by MOZGIII** [comment]
Looking good - that seems like what I need to get things running.
I'd propose to allow to explicitly configure whether to enable that new AWS credentials helper or not - and, maybe, the mode of operation (like with default credentials deductions mechanism, or via `github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds`).

**Comment by rusenask** [comment]
It would only do anything if environment variables are set. I think we also need region for the client:
```
	svc := ecr.New(session.New(), &aws.Config{
		Region: aws.String("us-east-2"),
	})
```
so maybe env variable `AWS_REGION=us-east-2` would be required. Without region client doesn't work.. :)

**Comment by MOZGIII** [comment]
I see, that's normal.

**Comment by MOZGIII** [comment]
Btw, will keel be able to detect that a tag like `myimage:master` is updated (re-tagged) and to update the deployment with an updated image? I understand how detection of the update would work, but is keel capable of updating the deployment with the new image but with the same tag?

**Comment by rusenask** [comment]
Yes, it requires `keel.sh/policy=force` to update non semver images

**Comment by rusenask** [comment]
Hi, pushed an alpha version to `keelhq/keel:alpha` with these changes. You can have a taste of it, there is still one thing left to implement. We need to reset tokens every 11 hours or so before they expire. I would probably also want to move SecretsGetter into a new credentials helper extension, but probably that's for another PR.. 

Currently things are quite busy in StorageOS before kubecon and dockercon so there isn't much time to sort this out.

**Comment by MOZGIII** [comment]
Thanks a lot, I'll give it a try. That should be enough to get things running.

So, maybe you're aware of a way we could force-restart keel every ~10 hours to make it work in fully unattended mode without that token expiry logic?

**Comment by rusenask** [comment]
could you please paste logs here? there should have been `extension.credentialshelper.aws: enabled`

**Comment by MOZGIII** [comment]
Here you go.
[logs.txt](https://github.com/keel-hq/keel/files/1951747/logs.txt)

Captured right after restart with `kubectl logs --namespace keel deployment/keel | head -n 100 > logs.txt` and redacted a bit.

**Comment by rusenask** [comment]
could you try pulling new alpha image? just pushed a small change. If it doesn't work, I will do some testing on aws k8s as well.

**Comment by MOZGIII** [comment]
Now it works, thanks

**Comment by emmekappa** [comment]
looking forward to have this in the master branch

**Comment by emmekappa** [comment]
@rusenask taking a look at your PR https://github.com/keel-hq/keel/compare/feature/ecr_registry_auth?expand=1#diff-9fae72804f41e956170441076fe98a62R40 the env var that you should check are `AWS_ACCESS_KEY_ID ` and `AWS_SECRET_ACCESS_KEY`

**Comment by MOZGIII** [comment]
I'd say letting AWS SDK to determine whether is has the configuration or now is a better way of doing it that manually checking for credentials. I think it should be possible to attempt to construct session and then to see if there's an error - and to only enable AWS credentials helper if there's none.

**Comment by emmekappa** [comment]
I agree

**Comment by rusenask** [comment]
I agree too. Any particular endpoint to check to ensure authentication is successful?

**Comment by rusenask** [comment]
Hi, new release is tagged (0.9.0-rc3). If you can check whether it's fine without token caching, we will make it 0.9.0. If not, I will add caching.

**Comment by MOZGIII** [comment]
Sure, I'll get to it tomorrow. I can tell upfront that requests to AWS are rate-limited, however I don't know how frequent polling is. More info here: https://docs.aws.amazon.com/AmazonECR/latest/userguide/service_limits.html
We have about 20 deployments now, so we have a rate limit of poll frequency about 4/20 = 0.2 per second, or ~12 times a minute. We should also have some reserve there, because keel is not the only user of the auth tokens.

**Comment by rusenask** [comment]
Adding cache to avoid these scenarios, with 20 images it would immediately hit that rate limit. https://github.com/keel-hq/keel/pull/203

**Comment by jkoivuko** [comment]
Tested briefly with the rc4. Approvals doesn't seem to work for me. It will announce need for approvals, but doesn't do deployment after approval. Without approvals deployments seem to work (using semver), all though I got one random 401 from ECR during the testing in the logs.

**Comment by rusenask** [comment]
Thanks @jkoivuko, can confirm issue with approvals. It's a bug in k8s cache, records get modified so after approvals are collected, keel doesn't detect any change in versions. There is a test now to get credentials from ECR 2000 times, cache seems to work.

**Comment by rusenask** [comment]
Hi @porkstart, do those env variables work with the aws cli? 
https://docs.aws.amazon.com/cli/latest/userguide/cli-environment.html

Maybe you don't have access rights to that registry?

**Comment by porkstart** [comment]
That appears to be the problem - at least in part. I managed to get semver working with `keel.sh/policy=all`but non-semver & `keel.sh/policy=force` still do not appear to work. Have you tried the non-semver updating and got it working?

**Comment by rusenask** [comment]
Can you show me an example of your application deployment file with non-semver config?

**Comment by porkstart** [comment]
Sure. The deployment is below. I noticed I am getting 

> msg="trigger.poll.WatchTagJob: failed to check digest" error="Get https://redacted-uid.dkr.ecr.eu-west-1.amazonaws.com/v2/redacted-repo/manifests/r-62a24f9: http: non-successful response (status=401 body=\"Not Authorized\\n\")" image="redacted-repo:r-62a24f9"

Which is strange because when I generate the credentials locally I can definitely access the manifests. When I delete the deployment and redeploy it with `keel.sh/policy=all` on 0.0.1 version it immediately gets updated to 0.0.2 as it should. 
The images in the repo are:

> r-62a24f9 created on 2018-04-30 15:08:53 +0100
> r-fffa649, 0.0.1, 0.0.2 created on 2018-04-30 15:19:36 +0100
> r-4696ce9 created on 2018-04-30 15:10:17 

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: some-app
    keel.sh/policy: force
    keel.sh/trigger: poll
  name: some-app
  annotations:
    keel.sh/pollSchedule: "@every 10s"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: some-app
    spec:
      containers:
      - name: api-server
        image: redacted-uid.dkr.ecr.eu-west-1.amazonaws.com/redacted-repo:r-62a24f9
        imagePullPolicy: Always
```

**Comment by rusenask** [comment]
Could it be that you need different permissions on aws for tags and digest
check?

**Comment by porkstart** [comment]
Ok. I think I misunderstood the non-semver tracking functionality, when I just add `latest` tag  and then deploy new image with `latest` tag, it updates correctly. I am guessing it is impossible for keel to determine that there is a newer image with a different tag otherwise.

**Comment by rusenask** [comment]
Correct, non semver tags only track the same tag based on digest. With
semver tags it can sort them and find the highest one.

If you used webhooks or gcr pubsub, force could update master to alpha to
beta to whatever :) I would want to add ecr sns since we already have aws
sdk. It would allow any tag updates, whatever is pushed to the registry.

**Comment by emmekappa** [comment]
after updating to `0.9.0-rc5` I start receiving again 

`http: non-successful response (status=401 body=\"Not Authorized\\n\")`

**Comment by porkstart** [comment]
Interesting, I checked and its same for us, however keel continues to work flawlessly despite the error messages.

**Comment by rusenask** [comment]
@emmekappa is this a full log message `http: non-successful response (status=401 body=\"Not Authorized\\n\")` ? I wonder whether aws-sdk is doing something without being asked :) Log messages for failed digest/tags look different and if actually gets everything it needs, we just need to silence this error.

**Comment by porkstart** [comment]
Not the case for us, we are getting the full messages (see below). Mind this is for working image that gets correctly updated by keel within 10s of tag change (using force).  

`time="2018-05-03T07:23:53Z" level=error msg="trigger.poll.WatchTagJob: failed to check digest" error="Get https://some-uid.dkr.ecr.eu-west-1.amazonaws.com/v2/some-repo/manifests/latest: http: non-successful response (status=401 body=\"Not Authorized\\n\")" image="some-image:latest`

We run keel with following IAM permissions, but as I said, everything seems to receive automatic updates properly:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "ecr:GetAuthorizationToken",
                "ecr:BatchCheckLayerAvailability",
                "ecr:GetDownloadUrlForLayer",
                "ecr:GetRepositoryPolicy",
                "ecr:DescribeRepositories",
                "ecr:ListImages",
                "ecr:DescribeImages",
                "ecr:BatchGetImage"
            ],
            "Resource": "*"
        }
    ]
}
```

**Comment by rusenask** [comment]
I will try IAM account, I have only been testing with my root account that has all permissions. However, this is bizarre :) Would probably make sense to add some debugs when watch **is** successful. Can you share the logs of what happens when you update the image? (it should show that new tag was found and looking for workloads to update)

**Comment by porkstart** [comment]
Hope this gives you some insight. There are currently 3 deployments managed by Keel, served from 3 separate repositories. As you can see its 20s between the error messages in this case which is double of the 10s poll scheduling policy. 

```
time="2018-05-02T23:53:58Z" level=error msg="trigger.poll.WatchTagJob: failed to check digest" error="Get https://someuid.dkr.ecr.eu-west-1.amazonaws.com/v2/some_repo_1/manifests/latest: http: non-successful response (status=401 body=\"Not Authorized\\n\")" image="some_repo_1:latest"

time="2018-05-02T23:54:58Z" level=info msg="trigger.poll.WatchTagJob: digest change detected, submiting event to providers" image="some_repo_1:latest" new_digest="sha256:d4f55f863dc59cca5838504d9574d8f64a397132f4b011a1af7c5a86706d9b54"

time="2018-05-02T23:54:58Z" level=info msg="provider.kubernetes: processing event" registry= repository=someuid.dkr.ecr.eu-west-1.amazonaws.com/some_repo_1 tag=latest

time="2018-05-02T23:54:58Z" level=info msg="provider.kubernetes.checkVersionedDeployment: keel policy found, checking resource..." kind=deployment labels="map[app:some_deployment_2 keel.sh/policy:force keel.sh/trigger:poll]" name=some_deployment_2 namespace=default policy=force

time="2018-05-02T23:54:58Z" level=info msg="provider.kubernetes: checking image" image="someuid.dkr.ecr.eu-west-1.amazonaws.com/some_repo_2:latest" kind=deployment name=some_deployment_2 namespace=default parsed_image_name="someuid.dkr.ecr.eu-west-1.amazonaws.com/some_repo_2:latest" policy=force target_image_name=someuid.dkr.ecr.eu-west-1.amazonaws.com/some_repo_1 target_tag=latest

time="2018-05-02T23:54:58Z" level=info msg="provider.kubernetes: images do not match, ignoring" parsed_image_name="someuid.dkr.ecr.eu-west-1.amazonaws.com/some_repo_2:latest" target_image_name=someuid.dkr.ecr.eu-west-1.amazonaws.com/some_repo_1

time="2018-05-02T23:54:58Z" level=info msg="provider.kubernetes.checkVersionedDeployment: keel policy found, checking resource..." kind=deployment labels="map[keel.sh/trigger:poll app:some_deployment_3 keel.sh/policy:force]" name=some_deployment_3 namespace=default policy=force

time="2018-05-02T23:54:58Z" level=info msg="provider.kubernetes: checking image" image="someuid.dkr.ecr.eu-west-1.amazonaws.com/some_repo_3:latest" kind=deployment name=some_deployment_3 namespace=default parsed_image_name="someuid.dkr.ecr.eu-west-1.amazonaws.com/some_repo_3:latest" policy=force target_image_name=someuid.dkr.ecr.eu-west-1.amazonaws.com/some_repo_1 target_tag=latest

time="2018-05-02T23:54:58Z" level=info msg="provider.kubernetes: images do not match, ignoring" parsed_image_name="someuid.dkr.ecr.eu-west-1.amazonaws.com/dodecant-auth-server:latest" target_image_name=someuid.dkr.ecr.eu-west-1.amazonaws.com/some_repo_1

time="2018-05-02T23:54:58Z" level=info msg="provider.kubernetes.checkVersionedDeployment: keel policy found, checking resource..." kind=deployment labels="map[keel.sh/policy:force keel.sh/trigger:poll app:some_deployment_1]" name=some_deployment_1 namespace=default policy=force

time="2018-05-02T23:54:58Z" level=info msg="provider.kubernetes: checking image" image="someuid.dkr.ecr.eu-west-1.amazonaws.com/some_repo_1:latest" kind=deployment name=some_deployment_1 namespace=default parsed_image_name="someuid.dkr.ecr.eu-west-1.amazonaws.com/some_repo_1:latest" policy=force target_image_name=someuid.dkr.ecr.eu-west-1.amazonaws.com/some_repo_1 target_tag     =latest

time="2018-05-02T23:54:58Z" level=info msg="provider.kubernetes: impacted deployment container found" parsed_image="someuid.dkr.ecr.eu-west-1.amazonaws.com/some_repo_1:latest" policy=force raw_image_name="someuid.dkr.ecr.eu-west-1.amazonaws.com/some_repo_1:latest" target_image=someuid.dkr.ecr.eu-west-1.amazonaws.com/some_repo_1 target_image_tag=latest

time="2018-05-02T23:54:58Z" level=info msg="provider.kubernetes: resource updated" kind=deployment name=some_deployment_1 namespace=default

time="2018-05-02T23:55:18Z" level=error msg="trigger.poll.WatchTagJob: failed to check digest" error="Get https://someuid.dkr.ecr.eu-west-1.amazonaws.com/v2/some_repo_1/manifests/latest: http: non-successful response (status=401 body=\"Not Authorized\\n\")" image="some_repo_1:latest"

```

**Comment by emmekappa** [comment]
@rusenask no the log is similar at the one posted by @porkstart:

```time="2018-05-03T09:28:18Z" level=error msg="trigger.poll.WatchTagJob: failed to check digest" error="Get https://XXXXXXXX.dkr.ecr.eu-west-1.amazonaws.com/v2/REPOSITORY/manifests/stage: http: non-successful response (status=401 body=\"Not Authorized\\n\")" image="REPOSITORY:stage"```

**Comment by emmekappa** [comment]
don't know if this may help to diagnose the problem but in my scenario I have 7+ pods that having keel force update configured and polling time set to 10s

**Comment by rusenask** [comment]
Hi, having a busy week. Has anyone tried tweaking their IAM permissions? 

@emmekappa it shouldn't matter how many pods there are, watchers would be setup based on number of images. I had an idea that maybe errors are from different regions, but from your errors it does seem the same registry and image.

**Comment by emmekappa** [comment]
@rusenask I'm running the `0.9.0-rc5` version and it's working even if my keel logs are full of 

```time="2018-05-09T11:08:21Z" level=error msg="trigger.poll.WatchTagJob: failed to check digest" error="Get https://XXXX.dkr.ecr.eu-west-1.amazonaws.com/v2/XXX/manifests/stage: http: non-successful response (status=401 body=\"Not Authorized\\n\")" image="XXX:stage"
time="2018-05-09T11:08:51Z" level=error msg="trigger.poll.WatchTagJob: failed to check digest" error="Get https://XXX.dkr.ecr.eu-west-1.amazonaws.com/v2/XXX/manifests/stage: http: non-successful response (status=401 body=\"Not Authorized\\n\")" image="XXX:stage"```

I think that keel runs two `WatchTagJob` for every pods that supports polling, but just one is actually working.

**Comment by rusenask** [comment]
Closing this down as ECR registry works, once I get a chance to get more info on this I will investigate those error messages
