### ISSUE TITLE
on a force + match-tag setting, valid semver pushes will still be deployed

### ISSUE THREAD

**Issue by azr** [keel-hq/keel#212]
For us this is nice because it means that any prod tag will reset our dev envs, but it's not really intended.

we could may be make it an option with: 
 * `keel.sh/match-tag: "true"` only deploy matching tags
 * `keel.sh/match-tag: "allow-valid-semver"` force match tag + deploy also on valid semver

**Comment by rusenask** [comment]
I think we just might want to finally add regexp matching for tags :) what do you think?

**Comment by azr** [comment]
Ah, yes, this will solve a lot of things !
So pre-check validation for the regexps when we find the config & then check if it matches after a trigger ?

I can do this ! :D

**Comment by rusenask** [comment]
maybe something like `keel.sh/match: "/^[0-9.]+/"` ?  Since it's not a policy or not an optional thing to policy (like `match-tag`) it should probably work independently :) 

It would for sure solve lots of different scenarios. Yeah, if you can - go for it :D

**Comment by azr** [comment]
Hi there, sorry I'm under a lot of pressure here and had little time to quickly fix for match-tag.
Will add that match when it goes down a bit.
