### ISSUE TITLE
Feature Request: Require re-approval for the same image tag

### ISSUE THREAD

**Issue by siddharthlatest** [keel-hq/keel#222]
Thanks for the great work on Keel!

I have a use-case where I am updating the same image tag via Slack approvals. Is there a possibility to add a manual approval each time the tag is updated?

**Reference:**

![](https://i.imgur.com/GnzBp78.png)

It asked for the approval first time, but not subsequently. The current behavior is obviously desirable in certain scenarios (where tags are treated as immutable releases etc.). However, in my scenario - I am doing CD on the same image tag.

One way l can think is applying a more narrower approval - to the specific commit SHA that the build is done for v/s an image tag.

**Comment by rusenask** [comment]
Hi, good idea regarding changed SHA! I think it totally makes sense and would be backwards compatible + wouldn't require any additional changes from the user. Will have a look at how best to add this.

**Comment by rusenask** [comment]
Hi, was about to start working on this issue. Does it even make sense to keep approvals once update is complete? 
For version updates previous approval doesn't add any benefit. And for unversioned ones it can introduce these scenarios where image is approved but in reality it has changed. Maybe we could just remove approval from internal store so the next one will have to be re-approved again?

**Comment by siddharthlatest** [comment]
> Maybe we could just remove approval from internal store so the next one will have to be re-approved again?

Would this be like a switch (perhaps an annotation like `keel.sh/re-approval: true`) which tells that re-approval should be required for each push? That should work as well.

**Comment by rusenask** [comment]
I think it's probably a security issue if we continue collecting approvals for the image if digest has changed. I will be modifying approvals manager to get digest if supplied and use it to reset votes (therefore will require approving again) if digest has changed.

**Comment by rusenask** [comment]
Fixed in https://github.com/keel-hq/keel/pull/229

**Comment by siddharthlatest** [comment]
Thanks @rusenask for this, I am going to try it! Also confirming that Docker Cloud's webhooks don't have the commit SHA (I am surprised, but well..).
