### ISSUE TITLE
Application deployed via Helm not updating

### ISSUE THREAD

**Issue by NAJ10** [keel-hq/keel#235]
Having problems getting keel to upgrade an application deployed via helm

When a new Docker image is pushed to GCR Keel detects the pubsub message and the kubernetes and helm providers start their processing. The Kubernetes provider correctly determines there is nothing to do. The helm provider logs
 "time="2018-07-08T18:30:47Z" level=info msg="provider.helm: current image version" container_image=eu.gcr.io/xxxx/bluesky-service current_version=0.1.33 name=bluesky-service namespace=default policy=all
"time="2018-07-08T18:30:47Z" level=info msg="provider.helm: checked version, deciding whether to update" container_image=eu.gcr.io/xxxx/bluesky-service current_version=0.1.33 name=bluesky-service 
"time="2018-07-08T18:30:47Z" level=info msg="provider.helm: impacted release tags found" container_image=eu.gcr.io/xxxx/bluesky-service policy=all target_image=eu.gcr.io/xxxx/bluesky-service target_image_tag=0.1.34
 "time="2018-07-08T18:30:47Z" level=error msg="provider.helm: failed to apply plan" error="rpc error: code = Unknown desc = cannot re-use a name that is still in use" name=bluesky-service namespace=default
Part of the last message appears to be coming from tiller although it is logged by keel.

The values.yaml contains
keel:
  policy: all
  trigger: poll
  pollSchedule: "@every 2m"
  images:
  - repository: image.repository
    tag: image.tag

In the values.yaml the image section contains
image:
  repository: eu.gcr.io/xxxx/bluesky-service
  tag: 0.1.33
  pullPolicy: Always

tiller version is 2.9.1
keel version is 0.9.5
kubernetes master version is GKE 1.10.4-gke.2

From the documentation at https://keel.sh/v1/guide/documentation#Helm it is hard to figure out how everything is meant to work. My CICD pipeline builds the docker image mentioned in the kubernetes deployment and pushes it to GCR. Everytime the image is pushed a tag is put on the image. The tag is the version number and increments in the following sequence, 0.1.29, 0.1.30, 0.1.31, 0.1.32, 0.1.33 etc. The build is not pushing the helm chart to GCR, Is it the helm chart that needs to be pushed to GCR?

The application was originally installed with
helm install --name bluesky-service --wait ./bluesky-service

The application can be manually upgraded with 
helm upgrade bluesky-service --wait ./bluesky-service

Is keel supposed to work by updating the image.tag value inside tiller? The CICD currently does not update any of the helm files during the build process. Is that correct?

**Comment by rusenask** [comment]
Hard to tell what happened, @rimusz  any ideas?

**Comment by rimusz** [comment]
no idea as well

**Comment by svnlto** [comment]
I've bumped into `cannot re-use a name that is still in use` a number of times before. IIRC it's to do with an invalid chart.

**Comment by tpatrascu** [comment]
We ran into the same thing, so we bumped the helm dependency to version 2.9.1 fom 2.8.1 and rebuilt keel version 0.9.5 and it worked.

**Comment by rusenask** [comment]
closing due to the lack of activity, if you are still experiencing this, please either reopen or create a new to so we can have a look :)
