### ISSUE TITLE
Hosting of the helm chart for installing keel

### ISSUE THREAD

**Issue by plumdog** [keel-hq/keel#236]
There is a chart in the main stable charts repo - https://github.com/kubernetes/charts/tree/master/stable/keel - but it is not up-to-date with the chart in https://github.com/keel-hq/keel/tree/master/chart/keel, most noticeably the one in stable doesn't work if you have RBAC enabled in your cluster.

It seems to me that either:
a) the chart checked in here should be pushed to https://github.com/kubernetes/charts/tree/master/stable/keel as often as possible
b) the chart checked in here should be hosted somewhere to make for easy installation

**Comment by rimusz** [comment]
The chart will soon be hosted in `keel-hq/charts` repo which is WIP on setting it up.
stable charts repo usually takes awhile to get PR checked/merged, we decided to have our charts repo, and time by time also push to stable one repo too.

**Comment by plumdog** [comment]
I totally appreciate the hassle of getting the chart into the stable charts repo, and doing it for every minor change is potential a waste of time.

However, I have come to use the stable charts repo as a list of interesting k8s applications to peruse, and I nearly dismissed keel and went looking for other solutions when the chart didn't install properly. So I'd be in favour of keeping the stable chart at least quite up to date, rather than letting it rot.

If the policy is "keep the chart in stable updated when possible", might it be worth adding something like that to the chart README? In general, I'm not really if it is OK to find someone's chart/manifest files and contribute them to the stable repo.

**Comment by rusenask** [comment]
Currently hosting on https://github.com/keel-hq/keel#lightning-quick-start and will add to kubeapps distributed registry once it's there.
