### ISSUE TITLE
Incomplete documentation on extra trigger types for non-cloud setups

### ISSUE THREAD

**Issue by caio1982** [keel-hq/keel#239]
The documentation on "Adding new trigger types" says it is coming soon, and I was wondering if it is possible/supported to have Keel running on-prem in my Kubernetes cluster without any external internet access at all. I mean, the images registry is in the local network (it's a financial institution, network policies are hardcore), so we can't use Docker Hub or GCP's registry. Is there a way to use Keel with that scenario without the documentation on how to add new trigger types? Is Docker's standard registry supported by any means?

**Comment by caio1982** [comment]
So you mean that if Kubernetes is already working with any given image registry, all that Keel will do is to monitor the deployments and it will transparently (without manual setup) fetch new images from the same registry Kubernetes knows about? That's neat.

**Comment by rusenask** [comment]
Yeah, it will also use whatever secrets (if any) you gave to Kubernetes for that particular registry :)
