### ISSUE TITLE
Object has been modified

### ISSUE THREAD

**Issue by cj-anthony** [keel-hq/keel#242]
Has anyone seen this behavior in keel before? We're running Keel on Azure Kubernetes Services and we have an Azure Container REgistry pushing webhooks to it. For the most part it works but on some images we get:

Operation cannot be fulfilled on deployments.apps \"deploymentname\": the object has been modified; please apply your changes to the latest version and try again" kind=deployment namespace=mynamespace update="latest->latest"

Our build simply pushes an image to ACR, I don't think anything would be modifying the kubernetes deployment before keel could get to it. Is there anything I can do to track this down?

**Comment by rusenask** [comment]
Hi, have a look at this function: https://github.com/keel-hq/keel/blob/master/provider/kubernetes/implementer.go#L117-L147, I once tried to add that RetryOnConflict but something went wrong, maybe it was a dependency issue. 
Also, you could also check in the logs, maybe you are getting several webhooks for the same image?

**Comment by cj-anthony** [comment]
Thanks, as soon as you said several webhooks for the same image something clicked. I think I know what it is. I'll come back and post if it's confirmed.

**Comment by rusenask** [comment]
I could add some event coalesce functionality, it would merge several incoming webhooks if they come it too fast :)

**Comment by rusenask** [comment]
I guess problem is solved? let's reopen if you still have this issue.
