### ISSUE TITLE
[bug] Issue parsing Helm configuration

### ISSUE THREAD

**Issue by MichielDeMey** [keel-hq/keel#247]
I've ran into an issue where Keel cannot parse one of my Helm configuration files.
Looking at the debug message, it's currently very difficult to determine the Chart that is causing the issue.

Could we extend the debug logs to include some more information regarding to which chart it's actually trying to parse?

```
...
time="2018-08-03T10:53:40Z" level=debug msg="trigger.poll.manager: performing scan"
2018/08/03 10:53:40 warning: destination for system is a table. Ignoring non-table value &lt;nil&gt;
time="2018-08-03T10:53:43Z" level=debug msg="trigger.poll.manager: performing scan"
2018/08/03 10:53:43 warning: destination for system is a table. Ignoring non-table value &lt;nil&gt;
...
```

**Comment by rusenask** [comment]
Yeah, for sure, although it's the first time I am seeing those warnings. Maybe some tab/spaces are there? Also, it might make sense to upgrade helm vendored dependencies. 

During the scan I would suggest adding some logging into which chart it's currently checking. Would you be able to add those logs or should I do that? (might only be able to do it over the weekend though). 

It's quite easy to run Keel locally with just ```keel --no-incluster``` command (connects to whatever cluster is configured for your kubectl)

**Comment by MichielDeMey** [comment]
A friend of mine also encountered the same parsing bug, which was due to a space/tab issue.
In his case however, the value was more description instead of `&lt;nil&gt` so he was able to find the misbehaving Chart easily.

I've quickly glanced at my Charts haven't found any issues yet, I'll try to run them through [kubeval](https://github.com/garethr/kubeval). Might be interesting for this project as well?

Unfortunately, my Golang skills aren't really up to production level yet so it might be best to leave the additional logging up to you guys.

I'll continue to check my Charts and I'll report back with some of my findings.
Thanks for the swift reply 👍

**Comment by rusenask** [comment]
If you are still encountering this, please reopen
