### ISSUE TITLE
Support for semver pre-release tag number

### ISSUE THREAD

**Issue by JochenGuck** [keel-hq/keel#252]
Right now Keel dos not upgrade a docker container if the pre-release tag number changes.
For example tag 0.1.0-unstable0001 is running. Tag 0.1.0-unstable0002 will not cause an upgrade.

Is it possible to configure/update keel that upgrades based on pre-release tag numbers are possible?

**Comment by rusenask** [comment]
It is not possible at the moment. I guess we could do comparisons according to https://semver.org/#spec-item-9. Quite difficult to know where the version is though. Any ideas?

**Comment by JochenGuck** [comment]
It seems that the semver library used supports correct semantic sorting. But it is suppressed by [`util/version/version.go#L133`](https://github.com/keel-hq/keel/blob/ce61b44888ff65d37c03bf856e9b002f7cef32a0/util/version/version.go#L133). What is the reason for this condition?

**Comment by rusenask** [comment]
I think the reason for this was mainly the auto update from semver to a version without the semver and from 1.0.0 to 1.1.0-rc1. I would be definitely in favor of updating semver versions with metadata inside them if the tag matches, according to your example: `0.1.0-unstable.1 -> 0.1.0-unstable.2`

**Comment by JochenGuck** [comment]
This transition 1.0.0 to 1.1.0-rc1 should be done with ALL so the following code at line 132 should do it.

```
if policy == types.PolicyTypeAll{
	return currentVersion.LessThan(newVersion) , nil
}
```
A new type for the pure semvar behavior is also an option.

**Comment by plumdog** [comment]
This is also relevant to my interests.

I think that being able to control this with a `keel.sh/...` label would perhaps be sensible, so we could retain existing behaviour, but allow something like `keel.sh/full-semver-compare: "true"` for example.

However, the code @JochenGuck linked to at https://github.com/keel-hq/keel/blob/ce61b44888ff65d37c03bf856e9b002f7cef32a0/util/version/version.go#L133 is now gone as of https://github.com/keel-hq/keel/commit/84239bd62ff0a557cab69b3bba44a3547f5f9745#diff-c4ffbd11b80f364ecdfd4bac91446380. Does that mean that this is fixed on master?

**Comment by rusenask** [comment]
hi, need to check but I think alpha tag is available or compile from master :) with policy "all" it should work with pre-release tags
