### ISSUE TITLE
Using Keel as a wekhook trigger to execute any custom Job

### ISSUE THREAD

**Issue by ysaakpr** [keel-hq/keel#266]
I have a scenario where i want to trigger a Kubernetes Jobs on an external trigger. An external trigger can be a git push, or manual trigger, which should call a webhook that Keel provides, and execute a defenit task/job in the k8s cluster, and the tasks can be basically anything, it may be upto the user, can run a helm install...or any other.

Can I use Keel in this situation ?? If usable, what is the suggested configurations ??

**Comment by rusenask** [comment]
Hi. No, Keel doesn't do this :) 

For event scripting Brigade might do the job https://github.com/azure/brigade/, although it's more like a DIY solution. But I think there are some examples given on how to do what you described.
