### ISSUE TITLE
Upgrade to 0.9.7 RBAC issues

### ISSUE THREAD

**Issue by WesleyCharlesBlake** [keel-hq/keel#267]
I had keel running on 0.9.5, and recently it auto upgraded to 0.9.7. I deployed keel through the helm charts, and noticed that the cluster role did not specify cronjobs in the RBAC policy, resulting in the following:

`failed to list *v1beta1.CronJob: cronjobs.batch is forbidden`

Whilst [this LOC](https://github.com/keel-hq/keel/blob/master/chart/keel/templates/clusterrole.yaml#L35) will resolve the RBAC issues, I need to update the charts on my side prior, and update the helm repo to the latest version of my chart (we run our own private helm repos)

Not really an issue, but more a question/suggestion to ensure breaking changes dont get introduced with automatic updates.

**Comment by rusenask** [comment]
Hi, sorry about that. I think watchers should also be a bit more forgiving, if permissions are not met, it could just not monitor specific resources.

**Comment by WesleyCharlesBlake** [comment]
Thanks! Not sure of how to introduce helm template changes in conjunction with keel automated updates. Perhaps if keel is update you could send a custom notification with links to required changes if a user is using the helm operator?

**Comment by rusenask** [comment]
I think sooner or later I will need to add a checkpoint server where Keel on startup reports to and maybe users could also supply their emails. No spam or anything, but important news on updates. Currently I have no idea how many keel installations are out there. From image pulls seems like a lot. ~9 months ago it was around 60 companies using it, now probably a lot more. 
It would be good to know what versions are running :)
