### ISSUE TITLE
AWS_REGION is set twice in Helm chart.

### ISSUE THREAD

**Issue by Antiarchitect** [keel-hq/keel#268]
https://github.com/keel-hq/keel/pull/246
https://github.com/keel-hq/keel/pull/238

Should we have both ecr: and aws: configurations or we can stick to one of them?

**Comment by rusenask** [comment]
Hi, I don't think AWS_REGION is used anymore, there was a PR for it that I think works out the region from the registry URL.

**Comment by Antiarchitect** [comment]
Nice to hear, should I close this issue?
