### ISSUE TITLE
Question: Best Practices for semver propagation?

### ISSUE THREAD

**Issue by jeremyjh** [keel-hq/keel#272]
Thanks for developing and supporting keel! Sorry to raise an issue for such a question, but I'm really curious what ideas may be out there around this and not sure where else to ask.

I'm using a helm chart to deploy my application. Right now I'm using static tags (e.g. master-latest) with the force option. I'd like to use semver, but I'm not sure how to reliably ensure the tag is set everywhere properly. 

What I mean is that say I use a policy patch, and in my `values.yaml` file if I start with `image: 0.0.1` and deploy with helm everything is in sync. Then I update my app, tag git with `0.0.2` and a tagged container build is pushed to the image repository and Keel triggers a deploy. Awesome. However, if I as a human forgot to update `values.yaml` with image tag `0.0.2` - the next time I deploy my chart, which may have nothing to do with image deployment (say adding an ingress option) then I will redeploy `0.0.1`. 

The best idea I can come up with to manage this is to have a script that is used for tagging, rather than manually tagging git. But I thought I'd ask what others are doing, or maybe there is another way to structure this so that the problem disappears.

**Comment by rusenask** [comment]
Hi! I usually just update the k8s manifest/helm chart with new environment variables and current image set, before letting it update automatically with the new image.

Totally agree regarding ops issue and probability that someone will forget to update the manifests. It would be nice to borrow some ideas from https://github.com/runatlantis/atlantis on automatic updates to the git repos :)

**Comment by jeremyjh** [comment]
Weaveworks `flux` also updates git; as I understand it their workflow is you use `fluxctl` to promote a new image and then flux updates your git repo. I like that there is no keelctl and everything is based on tags, but yeah maybe some kind of git update would be a nice feature to have at some point. Actually I'm not at all unhappy using static tags to control deployments; the more I think about automation around version numbers the trickier it gets.

Anyway thanks the response, I'll close this since its just a question and people can still respond even if its closed.

**Comment by rusenask** [comment]
Yeah, I really didn't want to introduce a CLI. I have some services that are being updated on "latest", the only downside is that you can't easily revert back to the previous version. Rollback did save me several times :)

**Comment by jeremyjh** [comment]
Yeah, I'm only going to have staging update on latest. Prod will have a separate static tag that is set manually.
