### ISSUE TITLE
Can't use keel when helm is configured to use TLS

### ISSUE THREAD

**Issue by maver1ck** [keel-hq/keel#275]
Hi,
I'm trying to use keel with TLS secured helm.
The result is following:
```
time="2018-09-18T15:09:21Z" level=error msg="provider.defaultProviders: failed to get tracked images" error="rpc error: code = Unavailable desc = transport is closing" provider=helm
```

**Comment by rusenask** [comment]
Helm client is created here https://github.com/keel-hq/keel/blob/master/provider/helm/implementer.go#L36, maybe only helm vendored dependencies would need an update?

**Comment by maver1ck** [comment]
I think it's more than this.
When using TLS connection you need to specify certificates.
https://github.com/helm/helm/blob/master/docs/tiller_ssl.md

**Comment by hedenface** [comment]
Was there ever any solution to this? Or was it determined to be a different issue?

**Comment by rusenask** [comment]
Helm TLS client wasn't implemented. It's quite a basic change, it would just require setting up Helm with TLS, sharing the certs to Keel pod and parsing the config. The TLS client preparation that needs to be copied is here: https://github.com/helm/helm/blob/master/cmd/helm/helm.go#L271. Would you be able to contribute this if you have a Helm Tiller with TLS already deployed? If no, maybe I could create it on a branch and tag it with `alpha` for you to test it?

**Comment by hedenface** [comment]
I think I'll take a stab at it, sure.

**Comment by hedenface** [comment]
Do we want to follow the ecosystem trend of assuming tls is enabled and forcing the user to override disabled? Or maintain backwards compatibility with existing systems, and save tls enabled for a major version?

**Comment by hedenface** [comment]
If my vote was worth anything, it'd be for the latter.

**Comment by rusenask** [comment]
let's leave it compatible as it is to avoid breaking changes. It can only be enabled if user supplies helm key and cert, right? I guess if those are supplied, then prepare the TLS client. Thanks!

**Comment by hedenface** [comment]
You're welcome. I would accept some branch or something to push to. Alpha or feature-tls or something, if possible.

**Comment by rusenask** [comment]
Workflow would be for you to fork this repository, then clone it to your $GOPATH/src/github.com/keel-hq/keel (so it builds locally). Once you are happy with the feature, open a pull request (https://github.com/keel-hq/keel/compare?expand=1). 

As for location where to push images, I usually push to any public repo under my default Docker username, from there it's easy to deploy. I imagine in this case certificates will already be prepared inside the Kubernetes cluster for Helm, right?

**Comment by hedenface** [comment]
To be quite honest, I'm really not sure where they are. I assume the tiller client cert is saved as a secret along with the ca.

But then every clients responsibility to maintain their own certificate locally. Locally in this case probably makes sense as a secret for keel.

I'll look more into how helm does it, and model it as close to it as possible.

**Comment by hedenface** [comment]
Hey it's been a while and this has been on my list to get to for a while now - but quite frankly haven't had the time at all. I think it's unlikely to assume I will anytime in the near future. I'd love to still help out - and plan on it when I can get to it, but wouldn't mind in any capacity at all if someone else went ahead and implemented this. Just wanted to update.

**Comment by rusenask** [comment]
with helm v3 released, we might not have tiller to connect soon enough! :)

**Comment by maver1ck** [comment]
Let's close it.
