### ISSUE TITLE
Keel not doing anything on Rancher 2.0 and docker private registry

### ISSUE THREAD

**Issue by miclefebvre** [keel-hq/keel#276]
I tried several ways of deploying Keel: Helm and deployment yml. 

I added labels to a deployment: 
keel.sh/trigger:poll
keel.sh/policy:force

I also tried with policies patch and all

Once keel is started, nothing ever gets updated.

The server start with logs: 

`time="2018-09-25T12:40:28Z" level=info msg="extension.credentialshelper: helper registered" name=aws
time="2018-09-25T12:40:28Z" level=info msg="bot: registered" name=slack
time="2018-09-25T12:40:28Z" level=info msg="keel starting..." arch=amd64 build_date=2018-09-01T115237Z go_version=go1.10.3 os=linux revision=087d7886 version=0.10.0
time="2018-09-25T12:40:28Z" level=info msg="provider.kubernetes: using in-cluster configuration"
time="2018-09-25T12:40:28Z" level=info msg="provider.defaultProviders: provider 'kubernetes' registered"
time="2018-09-25T12:40:29Z" level=info msg="extension.credentialshelper: helper registered" name=secrets
time="2018-09-25T12:40:29Z" level=info msg="bot.slack.Configure(): Slack approval bot is not configured"
time="2018-09-25T12:40:29Z" level=error msg="bot.Run(): can not get configuration for bot [slack]"
time="2018-09-25T12:40:29Z" level=info msg="webhook trigger server starting..." port=9300
time="2018-09-25T12:40:29Z" level=info msg=started context=buffer
time="2018-09-25T12:40:29Z" level=info msg=started context=watch resource=deployments
time="2018-09-25T12:40:29Z" level=info msg="trigger.poll.manager: polling trigger configured"
time="2018-09-25T12:40:29Z" level=info msg=started context=watch resource=cronjobs
time="2018-09-25T12:40:29Z" level=info msg=started context=watch resource=statefulsets
time="2018-09-25T12:40:29Z" level=info msg=started context=watch resource=daemonsets`

**Comment by rusenask** [comment]
Hi, can you show your application's deployment file? (at least that part where you set labels)

**Comment by miclefebvre** [comment]
I found out.

When we add labels to the Workload in Rancher UI, it adds them to the Pod Template(.spec.template) of the deployment instead of adding them to the metadata labels.

Now keels work #1.
