### ISSUE TITLE
Use imagePullSecrets from service account assigned to deployment spec

### ISSUE THREAD

**Issue by vkrivtsov** [keel-hq/keel#280]
Hi!

Currently, if i am not mistaken, keel use only explicitly defined imagePullSecrets in pod spec, but in case if imagePullSecrets is missed keel will not use [imagePullSecrets](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#add-imagepullsecrets-to-a-service-account) that assigned to service account that may defined on deployment spec. 

Would be nice if keel will support service account.

So i am as a operator can avoid explicit definition of imagePullSecrets for deployment 
 spec and use instead a service account that may used across many deployment specs

**Comment by vkrivtsov** [comment]
@rusenask my case assumes that keel use a poll trigger and need to fetch registry secrets in order to get access to docker registry

**Comment by vkrivtsov** [comment]
> it might work with the service account, you should test it as Kubernetes still probably populates imagePullSecrets even if you haven't :)

**Comment by rusenask** [comment]
but aren't those secrets automatically attached to the deployment by Kubernetes when service account is used?

**Comment by rusenask** [comment]
closing due to age
