### ISSUE TITLE
improve logging of Helm policy provider

### ISSUE THREAD

**Issue by The-Loeki** [keel-hq/keel#295]
Enabling the Helm provider triggers an `error` level log entry each second for each installed Helm chart without a Keel policy.

```
level=error msg="provider.helm: failed to get config for release" error="policy not specified" 
```

Specifying a wrong string is an `info` level message without decent traceback:
```
level=info msg="unknown policy 'dont'"
```

I'd love it if Keel would either ignore Helm charts without policies (which is kinda consistent with the annotation behaviour), or allow me to specify a kind of 'ignore this' policy.

**Comment by WesleyCharlesBlake** [comment]
Plus one on this too. I have a lot of helm charts which I do not necessarily want to update automatically (such as vault + consul) for eg. 

I've tried playing around with the debug and log levels but to no avail. Would be nice to explicitly determine which charts keel should watch, or ignore the rest.

**Comment by rusenask** [comment]
fixed
