### ISSUE TITLE
Add the document about policy.

### ISSUE THREAD

**Issue by hwchiu** [keel-hq/keel#300]
We can only found five types (all/major/minor/path/force) about usage of `policy` in the current website but there're still two un-document method, `glob` and `regexp`.

Those two types only recored in the issue or release note but I think it's helpful for users by adding more information about `glob` and `regexp` in the website/document.

Thanks

**Comment by rusenask** [comment]
Hi, it's still blocked by making it possible to specify policies in the annotations so regexp would be fully supported.

**Comment by hwchiu** [comment]
Got it, thanks

**Comment by rusenask** [comment]
added to docs
