### ISSUE TITLE
Update the published helm chart

### ISSUE THREAD

**Issue by hwchiuTW** [keel-hq/keel#303]
Hi. I found the stable published keel in the helm chart repo is out of dated.
https://github.com/helm/charts/tree/master/stable/keel

The published keel is based on the 0.9.5 and it doesn't support the erc as well.
Do we have any plan to update the stable helm chart from 0.9.5 to 1.2.0 ?

Thanks.

**Comment by rimusz** [comment]
As `helm/charts` is moving to distributed repo (central repo with remote repos) soon, doesn't make any sense to push the update there anymore.
We will setup a GitHub repo which will serve as helm repo, which you can use directly or via `helm/charts` new distributed repo

**Comment by hwchiuTW** [comment]
Thanks! got it.

**Comment by vsliouniaev** [comment]
If the only thing that changes is the location of the chart, does it still not make sense to update it?
