### ISSUE TITLE
Slack deployment notifications not working

### ISSUE THREAD

**Issue by WesleyCharlesBlake** [keel-hq/keel#308]
Since version 0.12 the slack deployment notifications aren't showing up.  I've gone through the logs and can't find anything. Even setting the level of logging to info or enabling debug I don't see anything that I can provide. When I enable approvals though, I get the notifications for approvals in Slack fine. Deployments are happening though as I run `keel get deployments` and I can see my releases have upgraded  . Any ideas or help will be greatly appreciated

**Comment by rusenask** [comment]
Hmm, will test it. Slack commands and notifications come through different paths :) Notifications require slack's webhook endpoint while commands work through Slack RTM connection.

**Comment by WesleyCharlesBlake** [comment]
hey @rusenask, on that, since notifications and commands are handled differently, is there anything specific I need to add to the keel deployment in terms of slack configuration? rightnow, Im just setting the bot Oauth token as per documentations. I have Webhooks enabled for the app in Slack, but I dont see how I can configure this in keel. Cheers!

**Comment by rusenask** [comment]
Sorry, my mistake. SLACK_TOKEN and SLACK_CHANNELS should be enough. Are you sure you have a bot user app configured? I think someone had a problem when created some other kind of Slack app token. Do you see any errors in the keel logs during the update?

**Comment by WesleyCharlesBlake** [comment]
OK, I just realised that theres a few ways you can create bot users in slack, one being by building an app, which gives you a bot user section with auth tokens etc. This is how I was creating my Bots.

I am creating my  bot user with [this](https://my.slack.com/services/new/bot) service now. will let you know if the problem persists :)

Thanks for the input!

**Comment by Anishmourya** [comment]
helm upgrade --install keel --namespace=kube-system keel-charts/keel --set slack.enabled=true,slack.token=xxxxxxxxxxx,slack.channel=test_channel_name,slack.botName=testbotname. working for me.
