### ISSUE TITLE
Ability to use PubSub triggers for GCR outside of GKE

### ISSUE THREAD

**Issue by ajwootto** [keel-hq/keel#323]
Hi, right now our docker images are hosted in GCR but our cluster is running in AWS. We are attempting to use PubSub triggers to notify of image changes, but currently the way Keel names its PubSub topics is using the cluster name obtained from what I assume is an API that only works in a GKE environment. Our AWS environment does not respond to this URL, so the different clusters we're running all end up with the same topic name in PubSub and conflicts occur. Is there a way to just override the cluster name with an environment variable instead of relying on this API? There doesn't seem to be a way to get the cluster name from the standard Kubernetes API (https://github.com/kubernetes/kubernetes/issues/44954)

**Comment by rusenask** [comment]
Hi, sorry, didn't expect Keel to be this far from GCR :) I will add an option to override the cluster name with an environment variable. However, it does seem that it would only show a warning?

```go
// MetadataEndpoint - default metadata server for gcloud pubsub
const MetadataEndpoint = "http://metadata/computeMetadata/v1/instance/attributes/cluster-name"

func containerRegistrySubName(projectID, topic string) string {
	cluster := "unknown"
	clusterName, err := clusterName(MetadataEndpoint)
	if err != nil {
		log.WithFields(log.Fields{
			"error":             err,
			"metadata_endpoint": MetadataEndpoint,
		}).Warn("trigger.pubsub.containerRegistrySubName: got error while retrieving cluster metadata, messages might be lost if more than one Keel instance is created")
	} else {
		cluster = clusterName
	}

	return "keel-" + cluster + "-" + projectID + "-" + topic
}

```

What do you see in your logs? Aren't subscriptions getting created at all?

**Comment by ajwootto** [comment]
Hi, yeah I realize it's an unusual use-case, it's sort of a long story ;)

The subscriptions get created but it uses "unknown" in place of the cluster name, so all the clusters end up sharing a topic. I basically just need a way to provide an override for that request's response.

**Comment by ajwootto** [comment]
Thanks for adding this @rusenask , I know it's a pretty specific feature request!

**Comment by rusenask** [comment]
Sure, I will add it to the docs. You can set `CLUSTER_NAME=mycluster` env variable for this

**Comment by magnusart** [comment]
Also is this is currently missing from the helm chart it seems?

**Comment by amq** [comment]
My case: I have multiple projects on GCP with the same cluster names. Basically, the projects act as environments (prod / staging / dev), so everything is exactly the same, apart of the project name itself.

Looking forward to this in helm.

**Comment by rusenask** [comment]
hi, it does seem like it just need a helm chart update to include that env variable?

**Comment by amq** [comment]
@rusenask yes, just `CLUSTER_NAME` in https://github.com/keel-hq/keel/blob/master/chart/keel/templates/deployment.yaml
