### ISSUE TITLE
Keel and Kubernetes not talking to each other using a plain HTTP (not secure) registry

### ISSUE THREAD

**Issue by caiobegotti** [keel-hq/keel#325]
Does this ring a bell? if I don't use `http://` in my image url Keel assumes the registry is `https://` since it is the DefaultScheme but this is not the case in my setup, I cannot change the registry setup to support HTTPS, so if I specify `http://` in the image url, Keel cannot even poll it because of this Kubernetes weird behavior I cannot explain yet:

```
Warning  InspectFailed  8s (x3 over 24s)  kubelet, kubworker1  Failed to apply default image tag "http://10.4.240.36:5000/<image tag>": couldn't parse image reference "http://10.4.240.36:5000/<image tag>": invalid reference format
 Warning  Failed         8s (x3 over 24s)  kubelet, kubworker1  Error: InvalidImageName
```

Of course I cannot let Keel assume `https://` because my registry won't support it, then Keel would complain with this: `http: server gave HTTP response to HTTPS client` in any case and I get stuck.

Anyone has seen this before or makes any sense out of this? It's keel:0.9.5 but I would be happy to test any patched or RC version ☺️ (oh, and Keel is also using a working imagePullSecrets, just in case it is relevant info).

**Comment by rusenask** [comment]
fixed in https://github.com/keel-hq/keel/pull/344, sorry it took ages!
