### ISSUE TITLE
GitLab webhook not working

### ISSUE THREAD

**Issue by Gambler13** [keel-hq/keel#332]
I tried to setup the GitLab webhook with keel (v 0.13.0).

First I activated the DockerHub notification in the GitLab config as described in the [GitLab Docs](https://docs.gitlab.com/ee/administration/container_registry.html#configure-container-registry-notifications).

This is my current configuration
```
......
### Registry notifications endpoints
 registry['notifications'] = [
   {
     'name' => 'my-registry',
     'url' => 'http://keel.mydomain.xyz/v1/webhooks/dockerhub',
     'timeout' => '500ms',
     'threshold' => 5,
     'backoff' => '1s',
     'headers' => {
     }
   }
 ]
........
```
After that I reconfigured the GitLab instance and pushed a new image to my GitLab registry.
The notification is triggered successfull, but keel response with an 400 Bad request. Unfortunately I can't see any error log statements in Keel.

```
2019-01-09_14:37:08.54698 time="2019-01-09T15:37:08.546903629+01:00" level=error msg="retryingsink: error writing events: httpSink{http://keel.mydomain.xyz/v1/webhooks/dockerhub}: response status 400 Bad Request unaccepted, retrying"
2019-01-09_14:37:08.54700 time="2019-01-09T15:37:08.54694839+01:00" level=warning msg="httpSink{http://keel.mydomain.xyz/v1/webhooks/dockerhub} encountered too many errors, backing off"
```

Any ideas what is going wrong?

**Comment by rusenask** [comment]
Hi, seems like you are using GitLab registry, the endpoint should be as described here https://keel.sh/v1/guide/documentation.html#Gitlab-webhooks:

```
http://keel.mydomain.xyz/v1/webhooks/registry
```

**Comment by Gambler13** [comment]
Of course, my fault. Thank you for your quick response.
