### ISSUE TITLE
Is keel checking my deployment?

### ISSUE THREAD

**Issue by paulmorabito** [keel-hq/keel#345]
Hi,

I'm using Rancher 2.1.6 and Kubernetes versions as follows:

Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:08:12Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.6", GitCommit:"b1d75deca493a24a2f87eb1efde1a569e52fc8d9", GitTreeState:"clean", BuildDate:"2018-12-16T04:30:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

I've installed Keel via helm. If I look at the logs for my Keel container, I can see a new watcher added for Keel:

level=info msg="trigger.poll.RepositoryWatcher: new watch repository tags job added"

In another deployment, to test, I added keel to poll and also update on all versions, checking hourly. The yaml for the deployment is below:

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "5"
    field.cattle.io/creatorId: user-qxrjg
    field.cattle.io/publicEndpoints: '[{"addresses":["192.168.1.52"],"port":30004,"protocol":"TCP","serviceName":"apps:youtube-dl-nodeport","allNodes":true}]'
  creationTimestamp: 2019-02-11T06:38:39Z
  generation: 6
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-apps-youtube-dl
  name: youtube-dl
  namespace: apps
  resourceVersion: "327902"
  selfLink: /apis/apps/v1beta2/namespaces/apps/deployments/youtube-dl
  uid: aacccbd2-2dc7-11e9-ad79-52c067ccfec7
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-apps-youtube-dl
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: 2019-02-12T06:41:57Z
        field.cattle.io/ports: '[[{"containerPort":8080,"dnsName":"youtube-dl-nodeport","kind":"NodePort","name":"8080tcp300041","protocol":"TCP","sourcePort":30004}]]'
        keel.sh/pollSchedule: '@hourly'
      creationTimestamp: null
      labels:
        keel.sh/policy: all
        keel.sh/trigger: poll
        workload.user.cattle.io/workloadselector: deployment-apps-youtube-dl
    spec:
      containers:
      - image: kmb32123/youtube-dl-server
        imagePullPolicy: Always
        name: youtube-dl
        ports:
        - containerPort: 8080
          name: 8080tcp300041
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /youtube-dl
          name: youtubedl-videos
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: youtubedl-videos
        persistentVolumeClaim:
          claimName: youtubedl-videos
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2019-02-11T06:38:40Z
    lastUpdateTime: 2019-02-11T06:38:40Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: 2019-02-11T06:38:39Z
    lastUpdateTime: 2019-02-12T06:42:04Z
    message: ReplicaSet "youtube-dl-6d7dbd5955" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 6
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1

However, for some reason I do not see a watcher being added in the Keel logs. How can I be sure Keel is actually checking hourly?

Any help would be very appreciated!

**Comment by rusenask** [comment]
hi, what's the image tag for the second one?

**Comment by paulmorabito** [comment]
There is no image tag specified as rancher defaults to 'latest' (I
believe). Should I specify?

**Comment by rusenask** [comment]
use policy `force` then, not `all` :) `all` is for semver tags

**Comment by paulmorabito** [comment]
I changed policy to force from all. Same issue. YAML export is again below:

apiVersion: v1
kind: Pod
metadata:
  annotations:
    cattle.io/timestamp: 2019-02-14T04:59:29Z
    cni.projectcalico.org/podIP: 10.42.1.147/32
    field.cattle.io/ports:
'[[{"containerPort":8080,"dnsName":"youtube-dl-nodeport","kind":"NodePort","name":"8080tcp300041","protocol":"TCP","sourcePort":30004}]]'
    keel.sh/pollSchedule: '@hourly'
  creationTimestamp: 2019-02-14T04:59:30Z
  generateName: youtube-dl-788bf6857-
  labels:
    keel.sh/policy: force
    keel.sh/trigger: poll
    pod-template-hash: "344692413"
    workload.user.cattle.io/workloadselector: deployment-apps-youtube-dl
  name: youtube-dl-788bf6857-sd8r8
  namespace: apps
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: youtube-dl-788bf6857
    uid: 4fbce2fd-3015-11e9-9365-525400233c29
  resourceVersion: "747489"
  selfLink: /api/v1/namespaces/apps/pods/youtube-dl-788bf6857-sd8r8
  uid: 50188a93-3015-11e9-9365-525400233c29
spec:
  containers:
  - image: kmb32123/youtube-dl-server
    imagePullPolicy: Always
    name: youtube-dl
    ports:
    - containerPort: 8080
      name: 8080tcp300041
      protocol: TCP
    resources: {}
    securityContext:
      allowPrivilegeEscalation: false
      capabilities: {}
      privileged: false
      readOnlyRootFilesystem: false
      runAsNonRoot: false
    stdin: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    tty: true
    volumeMounts:
    - mountPath: /youtube-dl
      name: youtubedl-videos
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-wpfq7
      readOnly: true
  dnsPolicy: ClusterFirst
  nodeName: 192.168.1.52
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: youtubedl-videos
    persistentVolumeClaim:
      claimName: youtubedl-videos
  - name: default-token-wpfq7
    secret:
      defaultMode: 420
      secretName: default-token-wpfq7
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2019-02-14T04:59:31Z
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: 2019-02-14T04:59:37Z
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: null
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: 2019-02-14T04:59:31Z
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID:
docker://5f9357678db17ae09548684d77e94b934deda520d6af519d7d917a2b9bbee41e
    image: kmb32123/youtube-dl-server:latest
    imageID: docker-pullable://kmb32123/youtube-dl-server@sha256
:cd1956b2e65772163f6c5cb3a9ec00c93090e69882c4bd758c01f3dbf8484237
    lastState: {}
    name: youtube-dl
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: 2019-02-14T04:59:36Z
  hostIP: 192.168.1.52
  phase: Running
  podIP: 10.42.1.147
  qosClass: BestEffort
  startTime: 2019-02-14T04:59:31Z

**Comment by rusenask** [comment]
I would suggest setting poll schedule to `10s` and just try pushing. If the image wasn't added for some reason, there should be an error log for some reason. Maybe your image is the same with some other deployment? They would only be added once then.

**Comment by paulmorabito** [comment]
What do you mean by try pushing? I'm not sure. I've set various increments
less than 1 minute, redployed the container multiple times. for whatever
reason, keel is not just registering it. Has anyone had this working with
Rancher? Possibly something is blocking it from seeing the container's keel
data? (different namespace?)

I checked and Keel is only running on one of my two nodes but it's the same
node as the above container is running on. There is no other container with
this image or name deployed anywhere else on the cluster. Is there anywhere
particular I can check for error logging?

**Comment by paulmorabito** [comment]
I have figured out the issue here.

If you add the labels via the Rancher GUI then it adds the
labels/annotations under "template". Even if you redeploy, these are never
actually set as far as I can tell.

if you edit the deployment yaml via kubectl and add the same annotations
then it works.

**Comment by rusenask** [comment]
Oh, I actually blogged about this issue here: https://webhookrelay.com/blog/2018/11/12/rancher-push-to-deploy-workflow/:

> Q: Can I set annotations/labels through the Rancher’s web UI when I am creating a new workload?
A: Unfortunately those end up in a pod spec and not the deployment so Keel won’t detect them and auto updates won’t work.

We could eventually read from pod spec as well and we will probably do that, since it will also allow a more specific control for which containers to update. Sorry I didn't remember this earlier!

**Comment by femolacaster** [comment]
> Hi,
> 
> I'm using Rancher 2.1.6 and Kubernetes versions as follows:
> 
> Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:08:12Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"} Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.6", GitCommit:"b1d75deca493a24a2f87eb1efde1a569e52fc8d9", GitTreeState:"clean", BuildDate:"2018-12-16T04:30:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
> 
> I've installed Keel via helm. If I look at the logs for my Keel container, I can see a new watcher added for Keel:
> 
> level=info msg="trigger.poll.RepositoryWatcher: new watch repository tags job added"
> 
> In another deployment, to test, I added keel to poll and also update on all versions, checking hourly. The yaml for the deployment is below:
> 
> apiVersion: apps/v1beta2 kind: Deployment metadata: annotations: deployment.kubernetes.io/revision: "5" field.cattle.io/creatorId: user-qxrjg field.cattle.io/publicEndpoints: '[{"addresses":["192.168.1.52"],"port":30004,"protocol":"TCP","serviceName":"apps:youtube-dl-nodeport","allNodes":true}]' creationTimestamp: 2019-02-11T06:38:39Z generation: 6 labels: cattle.io/creator: norman workload.user.cattle.io/workloadselector: deployment-apps-youtube-dl name: youtube-dl namespace: apps resourceVersion: "327902" selfLink: /apis/apps/v1beta2/namespaces/apps/deployments/youtube-dl uid: aacccbd2-2dc7-11e9-ad79-52c067ccfec7 spec: progressDeadlineSeconds: 600 replicas: 1 revisionHistoryLimit: 10 selector: matchLabels: workload.user.cattle.io/workloadselector: deployment-apps-youtube-dl strategy: rollingUpdate: maxSurge: 0 maxUnavailable: 1 type: RollingUpdate template: metadata: annotations: cattle.io/timestamp: 2019-02-12T06:41:57Z field.cattle.io/ports: '[[{"containerPort":8080,"dnsName":"youtube-dl-nodeport","kind":"NodePort","name":"8080tcp300041","protocol":"TCP","sourcePort":30004}]]' keel.sh/pollSchedule: '@hourly' creationTimestamp: null labels: keel.sh/policy: all keel.sh/trigger: poll workload.user.cattle.io/workloadselector: deployment-apps-youtube-dl spec: containers: - image: kmb32123/youtube-dl-server imagePullPolicy: Always name: youtube-dl ports: - containerPort: 8080 name: 8080tcp300041 protocol: TCP resources: {} securityContext: allowPrivilegeEscalation: false capabilities: {} privileged: false readOnlyRootFilesystem: false runAsNonRoot: false stdin: true terminationMessagePath: /dev/termination-log terminationMessagePolicy: File tty: true volumeMounts: - mountPath: /youtube-dl name: youtubedl-videos dnsPolicy: ClusterFirst restartPolicy: Always schedulerName: default-scheduler securityContext: {} terminationGracePeriodSeconds: 30 volumes: - name: youtubedl-videos persistentVolumeClaim: claimName: youtubedl-videos status: availableReplicas: 1 conditions:
> 
> * lastTransitionTime: 2019-02-11T06:38:40Z
>   lastUpdateTime: 2019-02-11T06:38:40Z
>   message: Deployment has minimum availability.
>   reason: MinimumReplicasAvailable
>   status: "True"
>   type: Available
> * lastTransitionTime: 2019-02-11T06:38:39Z
>   lastUpdateTime: 2019-02-12T06:42:04Z
>   message: ReplicaSet "youtube-dl-6d7dbd5955" has successfully progressed.
>   reason: NewReplicaSetAvailable
>   status: "True"
>   type: Progressing
>   observedGeneration: 6
>   readyReplicas: 1
>   replicas: 1
>   updatedReplicas: 1
> 
> However, for some reason I do not see a watcher being added in the Keel logs. How can I be sure Keel is actually checking hourly?
> 
> Any help would be very appreciated!

Hello @paulmorabito . How did you install Keel via helm? From Rancher UI?
