### ISSUE TITLE
No Update if Docker Image version non existing

### ISSUE THREAD

**Issue by JochenGuck** [keel-hq/keel#346]
I create a Deployment with a docker image which is not available at the docker repository. But there are Images available which match the update criteria of keel. I expect that keel updates to such of images.
This is unfortunately not working.

Keel provides the following error:
` time="2019-02-19T12:48:35Z" level=error msg="trigger.poll.RepositoryWatcher.addJob: failed to get image digest" error="Get https://*********/manifests/0.1.0-alpha0001: http: non-successful response (status=404 body=\"{\\\"errors\\\":[{\\\"code\\\":\\\"MANIFEST_UNKNOWN\\\",\\\"message\\\":\\\"manifest unknown\\\",\\\"detail\\\":{\\\"Tag\\\":\\\"0.1.0-alpha0001\\\"}}]}\\n\")" image="*********:0.1.0-alpha0001"'`

`time="2019-02-19T12:48:35Z" level=error msg="trigger.poll.RepositoryWatcher.Watch: failed to add image watch job" error="Get https://*********/manifests/0.1.0-alpha0001: http: non-successful response (status=404 body=\"{\\\"errors\\\":[{\\\"code\\\":\\\"MANIFEST_UNKNOWN\\\",\\\"message\\\":\\\"manifest unknown\\\",\\\"detail\\\":{\\\"Tag\\\":\\\"0.1.0-alpha0001\\\"}}]}\\n\")" image="namespace:dfce1a9e-10fa-4bbf-90a2-ec545143d3dd,image:*********,provider:kubernetes,trigger:poll,sched:@every 30m,secrets:[]" `

Is it possible to change this behavior?

**Comment by rusenask** [comment]
Are they in the same deployment? just multiple containers? 
Try pushing new image, maybe the working ones are actually tracked and it's just complaining about the ones it cannot get. If not, I will have a look at the workflow, how it adds the images for tracking.

**Comment by JochenGuck** [comment]
I create just a new deployment with a none existing Image version. 
e.g. 1.0.0 is not existing but 1.0.1 exists on the docker repository.
But keel is not able to update the from none existing 1.0.0 to existing 1.0.1.

**Comment by rusenask** [comment]
It might be a policy set to force/glob/regexp instead of minor/major?
