### ISSUE TITLE
Keel should not blindly trust webhook data

### ISSUE THREAD

**Issue by bokysan** [keel-hq/keel#347]
While testing I have discovered a potential flaw, which can destabilize a production system: Keel blindly trusts whatever is thrown at its webhook.

Use case:
------------------

- let's say I have a a deployment of application `example.org/test:v1.0.0`
- a malicious user (or an error) pushses a webhook notification to keel that `example.org/test:v2.0.0` is available
- keel will automatically update kubernetes deployments with the new version
- my services will die, as they won't be able to pull this (non-existent) tag from repository

Proposed solution
------------------

Keel should check if the given image is available in the repository before trying to update the deployments and abort update it it's not.

**Comment by rusenask** [comment]
I think we could add some shared secret if the registry supports. But by not checking in the registry it actually doesn't even need credentials to it greatly simplifying deployment and maintenance.

**Comment by rusenask** [comment]
New functionality is now available to add authentication to webhook request. But in general, if Keel can access your registry then it would make more sense to use polling instead of webhooks so it's always getting data from the registry :)
