### ISSUE TITLE
Slack approval replies are not working

### ISSUE THREAD

**Issue by maguire007** [keel-hq/keel#349]
I can't seem to get the slack integration with approvals working.  I have the notifications working, but the bot replies are not working. 

This is what I have done:

Created slack channel for approval and notifies.  Approval and notifications are being sent to the proper channel.  Approvals get sent to approvals, however when reply to approval type "keel get approvals" there is not response.

I have the legacy slack token key set in slack.token with helm deployment of keel.  I have created a slack bot called keel and the keel user associated with it.  I have added the keel users to the channel.  I see that the keel bot has several token for oauth appid, clientid,client secret, signing secret, and verification token. Are any of these needed?  Seems I am missing a step in this process.

In the docs https://keel.sh/v1/guide/documentation.html#Configuring-approvals-with-Slack it says to 

Step 2: supplying token to Keel
Use provided token as an environment variable in Keel’s deployment:

SLACK_TOKEN=token

Is this different than the -- set slack.token that I already set in the helm keel install? 

Any help would be appreciated.

**Comment by rusenask** [comment]
Hi, have you invited Keel into that channel on your Slack group?

**Comment by maguire007** [comment]
I got it working! I got caught into the slack bot/app/app-bot confusion and created an app bot rather than a custom bot.  Thanks for the help!
