### ISSUE TITLE
Keel can't find imagePullSecrets when using helm for some charts

### ISSUE THREAD

**Issue by Multiply** [keel-hq/keel#353]
In the helm integration, [there's an assumption](https://github.com/keel-hq/keel/blob/1f912825b99a361ae53aa7a5205728526d22b456/provider/helm/helm.go#L204) that the labels `app` and `release` is always set for pods managed by helm/tiller, which is not the case.

Following the [best practices for chart labels](https://github.com/helm/helm/blob/master/docs/chart_best_practices/labels.md) you'll end up with a different set of labels.

Ideally we should be able to simply set which imagePullSecrets to use, [kind of how it seems to have been approached in the beginning](https://github.com/keel-hq/keel/issues/50#issuecomment-318908833), instead of relying on the pods already in the cluster.

This could also fix a potential issue where a deployment/replicaset fails to create pods (due to various reasons), so we're kind of forcing the secrets down to keel.

Another approach would be allowing to override the default docker config using the helm chart that we used to deploy keel in the first place.

**Comment by rusenask** [comment]
hi, at the time of writing helm integration, those were the standard labels that helm would auto create for new charts. 
Yeah, I agree regarding the image pull secrets, it should be possible to specify it manually either through labels or helm values.yml

**Comment by rusenask** [comment]
Hi, I am bringing it back :)

**Comment by rusenask** [comment]
Available in the docs: https://keel.sh/docs/#helm-polling-private-registry
