### ISSUE TITLE
multiple helm releases configured to use different schedules for polling same the image

### ISSUE THREAD

**Issue by momkeller** [keel-hq/keel#355]
Hi, does keel support unique polling (and upgrade) schedules per helm release when more than one helm chart/release has keel configured to watch the same image repo?  

I set up the following scenario and it does not work as I would expect:

**ChartA - release named dev**
```
image
  repository: "myprivatereg/my-app"
  tag: "1.0.32"
keel:
  policy: patch
  trigger: poll
  pollSchedule: "@every 1m"
  images:
    - repository: image.repository
      tag: image.tag
```
**ChartB - release named qa**
```
image
  repository: "myprivatereg/my-app"
  tag: "1.0.32"
keel:
  policy: patch
  trigger: poll
  pollSchedule: "0 0 3,15 * * *" # every day at 3am and 3pm
  images:
    - repository: image.repository
      tag: image.tag
```

My expectations for this scenario are:
- dev release would be updated within minutes of a new image being added to the registry.
- qa release would only be updated every day at 03:00Z if a new image existed - ideally i'd would like this to run on the schedule "0 0 3,15 * * *" (3am & 3pm daily)

What appears to be happening, though i can't consistenly demonstrate this:
- both charts are updated based on the most recently updated schedule associated to the image repo irregardless of the keel configuration of each chart/release.
	
### Steps / timeline:

1. at 2019-03-20T22:00:00Z : upgrade charts with new poll schedules
    - helm upgrade --install dev ./ChartA --namespace dev-default --reuse-values --set-string keel.pollSchedule="@every 1m"	
      - dev now running image with tag "1.0.32"  
    - helm upgrade --install qa ./ChartB  --namespace qa-default  --reuse-values --set-string keel.pollSchedule="0 0 3 * * *"	  
      - qa now running image with tag "1.0.32"  

1. at at 2019-03-20T22:30:00Z: push new image to myprivatereg/my-app with tag "1.0.33"
    - between 22:30 03:00: release dev is NOT updated by keel to use this new tag

1. at 2019-03-21T03:00:00Z: 
    - release dev updated to use tag 1.0.33
    - release qa updated to use tag 1.0.33

1. at 2019-03-21T14:00:00Z: push new image to myprivatereg/my-app with tag "1.0.34"
    - between 14 and 15:00, dev is NOT updates to use .34

1. at 2019-03-21T15:00:00Z: update dev release to poll every 30s
    - helm upgrade --install dev . --namespace dev-default --reuse-values --set-string keel.pollSchedule="@every 30s"	  
    - between 15 and 15:30, dev still does NOT update to use "1.0.34"

### Keel Logs
 - using cmd: kubectl logs keel-677d8766fd-vtt6m -n kube-system --since-time=2019-03-21T00:00:00Z
```
time="2019-03-21T03:00:03Z" level=info msg="provider.kubernetes: processing event" registry= repository=myprivatereg/my-app tag=1.0.33
time="2019-03-21T03:00:03Z" level=info msg="provider.helm: processing event" registry= repository=myprivatereg/my-app tag=1.0.33
time="2019-03-21T03:00:03Z" level=info msg="policy for release dev-default/dev parsed: patch"
time="2019-03-21T03:00:03Z" level=info msg="policy for release kube-system/keel parsed: all"
time="2019-03-21T03:00:03Z" level=info msg="policy for release qa-default/qa parsed: patch"
time="2019-03-21T03:00:07Z" level=info msg="provider.helm: release updated" release=dev version=13
time="2019-03-21T03:00:14Z" level=info msg="provider.helm: release updated" release=qa version=8
time="2019-03-21T03:00:19Z" level=error msg="provider.defaultProviders: failed to get tracked images" error="context deadline exceeded" provider=helm
time="2019-03-21T03:00:19Z" level=info msg="trigger.poll.RepositoryWatcher: image no tracked anymore, removing watcher" image="namespace:qa-default,image:myprivatereg/my-app:1.0.32,provider:helm,trigger:poll,sched:0 0 3 * * *,secrets:[]" job_name=myprivatereg/my-app schedule="0 0 0 1 * *"
time="2019-03-21T03:00:19Z" level=info msg="trigger.poll.RepositoryWatcher: image no tracked anymore, removing watcher" image="namespace:kube-system,image:index.docker.io/keelhq/keel:0.13.1,provider:helm,trigger:poll,sched:@weekly,secrets:[]" job_name=index.docker.io/keelhq/keel schedule=@weekly
time="2019-03-21T03:00:19Z" level=info msg="trigger.poll.RepositoryWatcher: new watch repository tags job added" digest="sha256:4e2266bc67b410d458ac55c97f74796b118e37f5274a9fbcba8be942413bde23" image="my-app:1.0.33" job_name=myprivatereg/my-app schedule="0 1 * ? * *"
time="2019-03-21T03:00:24Z" level=info msg="trigger.poll.RepositoryWatcher: new watch repository tags job added" digest="sha256:c1cc93837164a6d47ba45902e222d167fa9864950fabd3adc5216d2b0ad20e27" image="keelhq/keel:0.13.1" job_name=index.docker.io/keelhq/keel schedule=@weekly
```

**Questions**:  
1. What am i doing wrong or what should my expectations be?  
1. Or, is there an issue with multiple helm releases configured to use different schedules for polling same the image?
1. Why do the logs show RepositoryWatcher stop and then restart tracking keel as well?

**Comment by rusenask** [comment]
Hi, sorry for the late reply, thought I already did it :) 

The way image tracking is implemented is that it will have a single watcher per docker image, unless you use non-semver tags such tas `:staging`, `:testing` and so on. Then, it sets up unique watchers for those repos. 

What we probably want here is a way to schedule "update windows". Such feature would be really useful for me as well! :)

**Comment by momkeller** [comment]
<<use non-semver tags>>gotcha.  thanks.  

multi semver tag based schedules would definitely be helpful.  maybe a way to have a docker image watcher that stores the tags it last retrieved and then separate cron jobs per release that uses those stored values.
