### ISSUE TITLE
Approvals: "bot couldn't recognise command"

### ISSUE THREAD

**Issue by kyle-johnson** [keel-hq/keel#356]
Got Keel installed via RBAC deployment file and connected to Slack.

It's picking up my new builds from GCB pubsub, but the approval command isn't working:
<img width="681" alt="approval required" src="https://user-images.githubusercontent.com/1007162/55183090-55c74d80-514c-11e9-9b22-681b248d661c.png">

The logs say:
```
time="2019-03-28T18:18:27Z" level=debug msg="handleMessage: bot couldn't recognise command" bot=slack command="approve deployment/default/frontend:v0.8.2" user=UBZDCK11D
```

`get approvals` succeeds:
<img width="1132" alt="get approvals" src="https://user-images.githubusercontent.com/1007162/55183130-6d9ed180-514c-11e9-9ebd-024d33fe2b8f.png">

Not really sure where to start tracking this down.

**Comment by rusenask** [comment]
Hi, did you set anything for approvals channel or is this in `#general`?

**Comment by kyle-johnson** [comment]
This is a keel-specific channel, with the bot invited:
```
- name: SLACK_CHANNELS
  value: "keel-notifications"
- name: SLACK_APPROVALS_CHANNEL
  value: "keel-notifications"
```

**Comment by rusenask** [comment]
hi, is there anything in the logs?  could there be a mismatch in the channel name? Also, try updating to the latest keel version :)

**Comment by rusenask** [comment]
seems like I have found the issue, apparently sometimes Slack through the websocket doesn't return info about the channel and we don't know on which chan the message arrived. I have changed implementation to use normal HTTP API to get that info but continuing to test it.

**Comment by rusenask** [comment]
Should be fixed with https://github.com/keel-hq/keel/pull/377

**Comment by kyle-johnson** [comment]
Latest build works! Thanks so much :-)
