### ISSUE TITLE
Webhook Relayd - Error 404 when approving deploy from slack - "http://localhost:9300/v1/webhooks/keel"

### ISSUE THREAD

**Issue by rdglinux** [keel-hq/keel#357]
Hi all!

I'm new keel user. 

I configured slack token and AWS credentials for ECR login with webhook relay as sidecar, when  build and push my docker image in ecr, the keel send notification to slack, and my application is updated correctly, this step is ok.

When enabled approvals to slack, does not work, the slack reponse to interact with bot 
 arrives in public webhook, and, arrives in the webhook relayd pod, but recive error 404.

**Slack approval message**

![image](https://user-images.githubusercontent.com/12894517/56136689-aa9afe80-5f69-11e9-850d-a0db1c949b9d.png)

**POD Log - Webhookrelayd**

```
$ kubectl logs keel-67596b6cc8-j95js webhookrelayd -n keel

{"level":"info","ts":1555332471.1408706,"msg":"webhook request relayed","destination":"http://localhost:9300/v1/webhooks/keel","method":"POST","bucket":"keel","status":404,"retries":0}
```
**Web Log - Webhook Relay**

![image](https://user-images.githubusercontent.com/12894517/56137123-825fcf80-5f6a-11e9-83b3-cd323964fa64.png)

I used this deployment file, and changed only Service LoadBalancer to ClusterIP. 

```
kubectl create -f https://raw.githubusercontent.com/keel-hq/keel/master/deployment/deployment-rbac-whr-sidecar.yaml
```

Any Idea? 
Thansk!

**Comment by rusenask** [comment]
Hi, you don't need webhook relay in your case, slack approvals go through slack's websocket client. Do you see anything in keel logs? I wonder whether it's complaining about unknown commands. Do "keel get approvals" or "keel get deployments" commands work?

**Comment by rdglinux** [comment]
Thanks for instant reply!

From keel pod, this commands does not work.

```
# keel logs
INFO[0001] extension.credentialshelper: helper registered  name=aws
INFO[0001] bot: registered                               name=slack
keel: error: unexpected logs, try --help

# keel get approvals
INFO[0001] extension.credentialshelper: helper registered  name=aws
INFO[0001] bot: registered                               name=slack
keel: error: unexpected get, try --help

# keel get deployments
INFO[0001] extension.credentialshelper: helper registered  name=aws
INFO[0001] bot: registered                               name=slack
keel: error: unexpected get, try --help
```

**Comment by rusenask** [comment]
What I meant was via Slack:

![image](https://user-images.githubusercontent.com/9080105/56140547-0332c180-5f93-11e9-91e1-3326a0ade060.png)

**Comment by rdglinux** [comment]
In my first screenshot, i sent "keel get approvals", but without response in slack.

My keel endpoint is not public, even so i don't need webhook relay for this?

I still don't understand how works. :/  ...

I'm going to do some new tests, without sidecar.

**Comment by rusenask** [comment]
issue was `SLACK_APPROVALS_CHANNEL` env variable for approvals channel set with `#` (`#approvals`).
