### ISSUE TITLE
Feature Request: Support for Namespace Tags

### ISSUE THREAD

**Issue by vugardzhamalov** [keel-hq/keel#361]
Hi there,

In my scenario I would like to have image(s) built from various branches/tags of my git repository deployed to dedicated Kubernetes namespace where namespace preferably is the same as my branch/tag name.

I was wondering if there is any way to specify which Kubernetes namespace Keel should deploy to once new docker image has been pushed to registry. As far as I can see Keel keeps deploying to the same namespace declared in the original deployment.

If it is not possible would you consider maybe special prefixes for image tags? Say something like 'keel-k8s-ns-' or similar, something that we can specify in order to instruct Keel which Kubernetes namespace it should deploy to utilizing the rest of the values from original deployment manifes? Thank you!

Please let me know if there is any further info required.

**Comment by rusenask** [comment]
hi, it's not really deploying, just updating existing images. Have you tried pushing to different tags based on your branches?

**Comment by vugardzhamalov** [comment]
Thanks @rusenask ,

Frankly not sure if I am on the same page. I have been successful in pushing images with multiple tags. And Keel picks them all up just fine depending on my policy config (in my case it is polling GCR) - as per original 'deployment.yml' manifest they will end up in the same cluster namespace. This is why I was wondering if I can make Keel proceed with deployment to a different cluster namespace...

Unless I've completely misunderstood the whole thing - the only way for me to go about it is to make separate deployment manifest per namespace - this might require Helm and Tiller and I would rather avoid these. Please let me know if you need further info.

**Comment by rusenask** [comment]
I guess separate deployment manifests with policies such as `glob:dev`, `glob:dev-2` are the only way to achieve it now.

**Comment by vugardzhamalov** [comment]
Thank you for clarification @rusenask,

I take it this not exactly in the scope of the project, at least for now I guess. Would you like me to close the ticket?

**Comment by rusenask** [comment]
Hi, yeah this seems like a bit out of scope as it would require some external configuration for keel. It tries to get everything it needs from the deployment manifest itself :)
