### ISSUE TITLE
Add UI into helm chart for testing

### ISSUE THREAD

**Issue by botzill** [keel-hq/keel#397]
Hi @rusenask .

Any chance to add UI into helm chart as well? I know you posted how to add it and seems quite easy, but I want to make sure I will not miss smth when adding it myself. 

Thx.

**Comment by rusenask** [comment]
Hi, UI only needs basic auth username and password to be set in order to enable those APIs. Helm chart already has them, can you try it out? Just change the tag to `latest` :)

**Comment by botzill** [comment]
Sorry, I do check https://github.com/keel-hq/keel/blob/master/chart/keel/templates/deployment.yaml and I see no UI setup, maybe I miss smth? Is it part of the keel itself? What is the port to access the UI, can we setup using ingress?

**Comment by rusenask** [comment]
UI is here https://github.com/keel-hq/keel/blob/master/Dockerfile#L6-L20 :) it's built together with Keel binary, port is the same server that we already had - 9300. So I guess your ingress PR will be very helpful here!

**Comment by botzill** [comment]
Ok,I see now, sorry for confusion. Yes, ingress will be helpful here.

Note that now I'm using ingress and using basic auth here. Maybe we may not
put restrictions to set those basic auth envs ?

**Comment by rusenask** [comment]
Unfortunately JWT auth is inbuilt into the frontend and due to certain management APIs I don't think it's good to have an option to run it without auth :D In theory you can set auth in both places but your proxy might string authorization headers.

**Comment by botzill** [comment]
OK, I'm testing it now and can't get the UI, does is ona specific path, like `/ui`?

Also, basic auth is applying only to UI of keel API as well? I have places where I'm using a hook to trigger updates, will this auth work there as well?

**Comment by rusenask** [comment]
It should be just on `/`, here are authenticated routes:
https://github.com/keel-hq/keel/blob/master/pkg/http/http.go#L133-L173
webhooks endpoints don't have auth.

Can you check Keel logs for this line https://github.com/keel-hq/keel/blob/master/pkg/http/http.go#L134 ?

**Comment by botzill** [comment]
OK, works! Sorry I had `IfNotPresent` setting on that's why it was taking the latest.

**Comment by rusenask** [comment]
nice :) also, you could expand chart so Keel gets a persistent volume mounted on `/data` so audit logs and approvals are preserved during restarts.

**Comment by botzill** [comment]
Yes, I can look into that.

btw, I get again in slack 

```
system event
Keel has started. Revision:
```

nu revision number.

**Comment by rusenask** [comment]
Yeah, saw that as well, will check it out. I think it's because I changed the build process to get correct sqlite binding so it can work in alpine image :/

**Comment by botzill** [comment]
I see, btw, will be easy to support PG as well for persistence?

**Comment by rusenask** [comment]
yep, very easy

**Comment by botzill** [comment]
OK, great. 

How much time does it take to build new helm chart/docker?

**Comment by rusenask** [comment]
do you mean keel docker container?

**Comment by botzill** [comment]
Yes, I mean this new merge we did, when can I install it, I see not yet in helm repo.

**Comment by botzill** [comment]
I still see 

```
helm search keel

keel/keel              	0.8.1        	0.14.0     	Open source, tool for automating Kubernetes deployment up...`
```

and I did `helm repo update`

**Comment by rusenask** [comment]
I see it has been built 30 minutes ago, is your repo set to https://charts.keel.sh?

**Comment by rusenask** [comment]
```
helm search keel
NAME       	CHART VERSION	APP VERSION	DESCRIPTION                                                 
keel/keel  	0.8.2        	0.14.0     	Open source, tool for automating Kubernetes deployment up...
```
Seems to be the version that you set in the PR

**Comment by botzill** [comment]
OK, now I see it also, thx. Check new PR with persistence.

**Comment by botzill** [comment]
@rusenask there is an issue if I try to set basic auth on both ingress and UI. It asks for auth for every resource from the server. I was wondering if the auth from UI can as well be added to API?

**Comment by rusenask** [comment]
it's already there, API accepts both basic auth and JWT tokens. So the workflow is:
1. When you first login via UI it sends a POST request to the API and gets a JWT token
2. It persists JWT token in browser's local storage
3, Any further requests use JWT auth so we don't store user's credentials anywhere

I suspect it's your ingress is asking for authentication on every request?

**Comment by botzill** [comment]
Yes, ingress is asking for auth. The reason I set auth to ingress is to make calls to API hook. So, I want to make a request to https://mydomain/v1/webhooks/native using the same auth as for UI, does it work this way?

**Comment by rusenask** [comment]
what if in your ingress you create a separate entry for `/v1/webhooks/native` with authentication enabled?
Otherwise, we can have an option controlled via env var to enable authentication for webhook endpoints.

**Comment by botzill** [comment]
Well yes I can do that with ingress I guess, but would be really nice to have all in one place. If it's too much work, I can add that for now in ingress.

**Comment by botzill** [comment]
OK, I see now: https://charts.keel.sh/keel-0.8.3.tgz is present but: `helm search keel` still gives me old version. Does it require an extra action to see it?
