### ISSUE TITLE
helm provider: context deadline excedded

### ISSUE THREAD

**Issue by cybersiddhu** [keel-hq/keel#429]
Hi,
I am using the latest version of keel and using helm provider to get a slack channel based approval for my deployments. However, for every dockerhub webhook there's error reported in the keel log.
```
time="2019-08-16T01:27:11Z" level=error msg="provider.helm: failed to process event" error="context deadline exceeded" image=dictybase/modware-annotation tag=refactor-purge-annotation-interface-dbc8f59
time="2019-08-16T15:43:48Z" level=error msg="provider.helm: failed to process event" error="context deadline exceeded" image=dictybase/modware-annotation tag=refactor-purge-annotation-interface-8bbe45d
```
Any idea how to fix or what's going wrong here.

**Comment by rusenask** [comment]
Hi, it's probably due to keel not connecting to tiller. Could you try supplying that tiller address to keel as per example https://github.com/keel-hq/keel/blob/master/chart/keel/values.yaml#L24-L25 ?
