### ISSUE TITLE
 kube user and token 

### ISSUE THREAD

**Issue by teng1** [keel-hq/keel#445]
Hi, is it possible to provide a kube user token to keel rather than the requirement for a clusterRole? 

We are using a multi-tenanted cluster with full access to assigned namespaces but not access to the cluster RBAC to create the role bindings etc. Instead we have a token for use on CI servers. and rather interested in use of Keel for deploying helm(3) charts to our namespaces.

Thanks

**Comment by teng1** [comment]
starting in --no-incluster essentially has the effect of achieving this

**Comment by salanki** [comment]
I'm a bit curious on how you got this to work. Does Keel run if you give it an account where it cannot list namespaces at the cluster scope?
