### ISSUE TITLE
feature request: Helm 3 Support

### ISSUE THREAD

**Issue by teng1** [keel-hq/keel#449]
Hi,
Would be great if Helm 3 support could be added, it's in tiller-less form now and progressing through Beta releases, potentially could be added as a provider? For the restrictions I'm working within, it would also be good to have an option for use of credentials stored in secrets.
Thanks

**Comment by rusenask** [comment]
Hi, yeah we should totally do that :) Need to investigate a bit more in using it as an imported package :)

**Comment by AWKIF** [comment]
Helm 3 is out, would love if keel can support it :)
cheers !

**Comment by bokysan** [comment]
Any news / progress on this issue? Does anyone have any workarounds?

How can we help?

**Comment by neurosis71** [comment]
That would be really awesome to have this !

**Comment by alexcasutt** [comment]
+1

**Comment by dankirkpatrick** [comment]
Is anyone at keel-hq working on this?  Looks like the git repo hasn't had a commit since Nov. 3.  Has Keel been abandoned?

**Comment by rusenask** [comment]
Hi, not abandoned but as we are not using helm itself there's very little priority for this. I think in the slack channel someone said that he's working on helm 3 support and might open a PR.

**Comment by bokysan** [comment]
Last post on Slack was not very promising.

![image](https://user-images.githubusercontent.com/4567693/73064924-9560e200-3ea2-11ea-9395-1236b1d139b2.png)

Happy to help, but don't know where to start -- anything you can suggest where to get started would be most helpful.

**Comment by rusenask** [comment]
I think easiest way would be to:

1. Add a new package helm3 here https://github.com/keel-hq/keel/tree/master/provider
2. The new helm3 pkg would have to implement this interface https://github.com/keel-hq/keel/blob/master/provider/provider.go#L13-L18 to basically react to new image events (update charts) and also scan existing installed charts so it could report back what images are being tracked

**Comment by LucaPrete** [comment]
Hello guys! Is there any news on this? Helm3 is pretty much a standard already, and it's a shame a great project like keel does not support it, yet...

I don't know the keel mechanics well, but, any way I can help? I saw the suggestions above but I'm not sure how's driving the effort. Don't want to overlap with somebody else.

**Comment by bokysan** [comment]
@LucaPrete I was planning on tackling this issue, but haven't had the time yet. Hopefully I can start work in the next two weeks -- unless somebody else already did?

**Comment by LucaPrete** [comment]
Thanks. The cool thing is that there's much to remove rather than add. And
the only thing that has changed in the install command is the lack of the
-n (or --name) parameter - which now -instead- only requires the name.

-Luca

Il giorno lun 10 feb 2020 alle ore 11:47 Boky <notifications@github.com> ha
scritto:

**Comment by rusenask** [comment]
since we are using helm libraries directly it might be difficult to version two different things :) does helm3 work with existing charts? (I think it does)

**Comment by LucaPrete** [comment]
Yes, it does! ...It worked for all my charts, although it might me
worthwhile to double check if there are corner cases.

Il giorno mar 11 feb 2020 alle ore 12:49 Karolis <notifications@github.com>
ha scritto:

**Comment by sbussard** [comment]
Helm 3 is great. I'd love to see Keel support it.

**Comment by Hajar1** [comment]
Please support this!

**Comment by mavimo** [comment]
@rusenask I'm starting to work on it, there are a few enabler in order to have opportunity to have multiple version of helm lib referenced in this repo, I'll open PRs to fix it :)

**Comment by nnt1054** [comment]
I also tried working on adding Helm3 support by adding a helm3 provider interface as someone else suggested above.
I believe the main blocking issue I ran into was that the [helm3](https://pkg.go.dev/mod/helm.sh/helm/v3@v3.2.1) go module requires a different k8s.io/client-go major version from the one keel is currently using.
The helm.sh/helm/v3 [go.mod](https://github.com/helm/helm/blob/master/go.mod) file lists k8s.io/client-go v0.18.2 while keel's [go.mod](https://github.com/keel-hq/keel/blob/master/go.mod) uses k8s.io/client-go v11.0.1.
Attempting to build an empty go module that requires both helm.sh/helm/v3 and k8s.io/client-go v11.0.1 fails to build, as well as trying to build keel with k8s.io/client-go v0.18.2.
Has anyone else made any progress on this or have any ideas with resolving the dependency issues?

**Comment by jakesyl** [comment]
I'm deploying with helm 3 now totally fine

**Comment by mavimo** [comment]
@nnt1054 using `replace` to override and use the most recent module doesn't work? Is something related to keel itself or other deps (eg helm2)? If is keel only maybe we can try to upgrade it..

**Comment by nnt1054** [comment]
@jakesyl keel.sh shouldn't be compatible with helm v3 yet unless I missed something?
@mavimo Never mind, I was able to get both helm v2 and helm v3 go client libraries installed at the same time by upgrading some of keel's dependencies.  I'm using helm.sh/helm/v3 v3.1.2 and upgraded k8s.io/kubernetes from v1.14.2 to v1.16.10 along with corresponding k8s.io modules to v0.16.10.  I'll check back in once I've finished adding a new helm3 provider.

**Comment by rusenask** [comment]
I think it's totally fine to update all helm dependencies (especially k8s client as we aren't using anything special from there)

**Comment by rusenask** [comment]
@nnt1054 could you share your branch? I might be able to help integrating

**Comment by nnt1054** [comment]
@rusenask https://github.com/nnt1054/keel/tree/feature/helm3_provider
This branch should be compatible with Helm v3 now.  `make test` and `make e2e` pass all the tests, although I may have needed to fix a few tests with the dependency updates.  I manually tested/checked most of the basic features using minikube with kubernetes v1.18.2.

Let me know if this there's any changes you'd like to see or if I should try and make a pr now!

**Comment by mavimo** [comment]
@nnt1054 nice!! IMHO you can start to create a PR so you can receive feedbacks from others and in the meantime (if you have time) fix the missing parts

PS: thx for the work, this feature is really appreciated from many users in the community!!

**Comment by rottenbytes** [comment]
Awesome; is there a way for me test so I can try it and hopefully provide some feedback ?

**Comment by nnt1054** [comment]
@rottenbytes you should be able to clone the branch from my fork from: https://github.com/nnt1054/keel/tree/feature/helm3_provider
Afterwards you can build your own docker image and use that for testing.

**Comment by rottenbytes** [comment]
image starts fine, but I get the following message in a loop : 
> level=error msg="provider.defaultProviders: failed to get tracked images" error="context deadline exceeded" provider=helm

**Comment by nnt1054** [comment]
Did you make sure to set helmProvider.version="v3" when installing the keel chart on your cluster?  The image is meant to setup either Helm v2 or Helm v3, but not both at the same time.  The `provider=helm` field of your error message is suggesting your keel deployment is using Helm v2, else it should say `provider=helm3`

**Comment by jvanwygerden** [comment]
@nnt1054 is your work something that can be consumed today (or that you you would like support from in Beta-testing) ? 

Helm 3 support is an important feature

**Comment by nnt1054** [comment]
@jvanwygerden Ideally my changes should be ran against some more comprehensive testing, especially to double check that my changes and updated dependencies are still backwards compatible with preexisting configurations.  I only sparsely tested the helm3 functionality on a local minikube cluster and not much else.
Although, I believe it’s up to the reviewers/maintainers to decide on how to proceed with adding the Helm v3 support anyway.

**Comment by rottenbytes** [comment]
@nnt1054 

> Did you make sure to set helmProvider.version="v3" when installing the keel chart on your cluster? The image is meant to setup either Helm v2 or Helm v3, but not both at the same time. The `provider=helm` field of your error message is suggesting your keel deployment is using Helm v2, else it should say `provider=helm3`

Yes I did, I triple checked my `values.yaml` which is the following : 
```yaml
---
gcr.enabled: "true"
gcr.projectId: "--redacted--"

helmProvider:
  version: "v3"
  enabled: true

image:
  repository: rottenbytes/keel
  tag: helm3
```

my kubernetes version : v1.16.8-gke.15

**Comment by nnt1054** [comment]
@rottenbytes do you mind sharing more of the logs from your keel pod (`kubectl logs keel-...`)?  Specifically looking for which providers were registered:
```
time="2020-06-09T08:08:14Z" level=info msg="provider.defaultProviders: provider 'kubernetes' registered"
time="2020-06-09T08:08:14Z" level=info msg="provider.defaultProviders: provider 'helm3' registered"
```
Also just to verify, are you installing the helm chart from keel's helm repo (https://charts.keel.sh) or are you installing the local chart in the `/chart/keel` subpath of my fork?  Setting helmProvider.version="v3" with keel's current helm chart would still make it use Helm v2.

**Comment by rottenbytes** [comment]
haaa. that's it :) I'm using the official chart.

**Comment by rottenbytes** [comment]
No more errors, but I can't get the system to work (I have only used it on resources before, not on helm charts; which is not relevant to this very issue)

**Comment by rottenbytes** [comment]
It seems that it does not pick the chart. My chart : 
```yaml
---
replicaCount: 1

image:
  repository: eu.gcr.io/xxx/myimage
  tag: test
  pullPolicy: Always
  pullSecret: "gcr-json-key"

keel:
  policy: force
  trigger: poll
  pollSchedule: "@every 1m"
  images:
    - repository: image.repository
      tag: image.tag
      imagePullSecret: image.pullSecret
```

but keel never picks up the image to be watched

**Comment by nnt1054** [comment]
hmm, are there any relevant log warning or error messages from your keel pod? (`kubectl logs keel-...`)?
What namespaces are you deploying keel and your eu.gcr.io/xxx/myimage to?
Also are you are able to test if keel still won't pick up/track your image if you deploy the image via just a kuberentes deployment manifest file? (https://keel.sh/docs/#kubernetes-example)  Would be helpful in trying to isolate what exactly is causing your issue, since I haven't tested with using a gcr.io repo or pullSecrets yet.

**Comment by rottenbytes** [comment]
Nothing in the logs, no errors.

keel goes into its own namespace (`keel`) and the test image to her own (named `tracing`).
keel pick ups the change when I use a simple deployment directly, with no problem, on a gcr.io image.

**Comment by rottenbytes** [comment]
I got keel to see my release when putting it in the same namespace than keel (the `keel` namespace), which is obviously not something I want to do :)

**Comment by rottenbytes** [comment]
LGTM

**Comment by unixfox** [comment]
Now that https://github.com/keel-hq/keel/pull/507 got merged. Can this issue be closed?

**Comment by ford-thomas-w** [comment]
Would be great to have some info in the Guide on how to use the Helm 3 provider.  Did not work for me and from looking at the  templates I'm guessing that helmDriver is required for v3?  But I don't know what to put there.  Can you provide an example?

```
helmProvider:
  version: "v3"
  enabled: true
  helmDriver: '???'
#or,   helmDriverSqlConnectionString: '???'
```

**Comment by rusenask** [comment]
hi, just doing some additional maintenance on that part, will be able to provide more info soon. 

Those 
```
helmDriver: '???'
#or,   helmDriverSqlConnectionString: '???'
```

Should be optional, only used if you are using them with your helm, otherwise no need to set them.
