### ISSUE TITLE
Integration with kustomize

### ISSUE THREAD

**Issue by posix4e** [keel-hq/keel#468]
We are currently trying to decide if we wanna move to helm 3 or do everything we do through kustomize. Currently with helm 2 (#95), we have to have an out of keel based process for updating things like environment variables to manage the charts. I wonder if moving to kustomize would make any of this type of things easier for keel?

**Comment by rusenask** [comment]
Hi @posix4e, sorry for the 3 month delay :) I guess at this time you have solved your issue, which path have you chosen? 
I personally don't use Helm so would have went with the other option.
