### ISSUE TITLE
Polling from private repository with token authentication fails with 401 UNAUTHORIZED

### ISSUE THREAD

**Issue by dennismeissel** [keel-hq/keel#472]
Provider: Kubernetes.
Registry: Private docker registry with token authentication ([cesanta/docker_auth](https://github.com/cesanta/docker_auth))

The secret with a name `dockerregistry` was created with `kubectl create secret` then added to Pod spec:

```yaml
spec:
  containers:
  - image: dockerregistry.mysite.com/myprivateimage:0.1.1
  imagePullSecrets:
    - name: dockerregistry
```

`kubectl apply -f filename` pulls images and installs everything correctly

But if I'm trying to add keel, I'm getting `401 UNAUTHORIZED` in keel logs:

```
time="2020-01-24T11:26:37Z" level=error msg="trigger.poll.RepositoryWatcher.Watch: failed to add image watch job" error="Get https://dockerregistry.mysite.com/v2/myprivateimage/manifests/0.1.1: http: non-successful response (status=401 body="{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"repository","Class":"","Name":"myprivateimage","Action":"pull"}]}]}")" image="namespace:default,image:dockerregistry.mysite.com/myprivateimage:0.1.1,provider:kubernetes,trigger:poll,sched:@every 1m,secrets:[dockerregistry]"
time="2020-01-24T11:26:37Z" level=error msg="trigger.poll.manager: got error(-s) while watching images" error="encountered errors while adding images: Get https://dockerregistry.mysite.com/v2/myprivateimage/manifests/0.1.1: http: non-successful response (status=401 body="{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"repository","Class":"","Name":"myprivateimage","Action":"pull"}]}]}")"
time="2020-01-24T11:26:40Z" level=error msg="trigger.poll.RepositoryWatcher.addJob: failed to get image digest" error="Get https://dockerregistry.mysite.com/v2/myprivateimage/manifests/0.1.1: http: non-successful response (status=401 body="{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"repository","Class":"","Name":"myprivateimage","Action":"pull"}]}]}")" image="myprivateimage:0.1.1" password="**********" username=testuser
```

As you can see, keel gets the secret and username/password. But it doesn't work.

Also, if I find these requests in logs of the docker-registry, I see these errors:
```
error authorizing context: authorization token required
...
error authorizing context: malformed token
```

**Comment by dennismeissel** [comment]
I debugged a bit the project.

As I understood, if the client gets 401 unauthorized, the error just will be returned.

That means, that [Docker Registry v2 authentication via central service](https://github.com/docker/distribution/blob/master/docs/spec/auth/token.md) is not supported right now :(

**Comment by dennismeissel** [comment]
## **Expected behaviour:**

1. If the registry returns **401 unauthorized**, client takes `Www-Authenticate` header from response and parses `realm`, `service` and `scope`.
2. Client sends the second request to the realm server with `service` and `scope` as url-encoded parameters
3. Client takes `access_token` from the realm server response
4. Client sends the new request to the registry with the header `Authorization: Bearer {access_token}`

**Comment by dennismeissel** [comment]
I found out, why is it failing.

Docker-Registry-Client used in this project gets only `token` field in the token-authorization.
Howewer it should also accept `access_token` field (according to [Token Authentication Specification](https://docs.docker.com/registry/spec/auth/token/#token-response-fields))

I've created a [pull-request](https://github.com/heroku/docker-registry-client/pull/74) that solves this problem

**Comment by rusenask** [comment]
yeah it does explain the failures :) good job! :)

**Comment by dennismeissel** [comment]
@rusenask,
Thanks for merging.
When these changes will affect the docker image of keel?

**Comment by dennismeissel** [comment]
As I see, it's already there. Thank you.
