### ISSUE TITLE
Kubernetes deployment template api upgrade required from v1beta2 to v1

### ISSUE THREAD

**Issue by rchenzheng** [keel-hq/keel#473]
```
$ kubectl apply -f https://sunstone.dev/keel\?namespace\=keel\&username\=admin\&password\=admin\&tag\=latest
error: unable to recognize "keel": no matches for kind "Deployment" in version "extensions/v1beta2"
```

The deployment API is now on v1, the deployment-template.yml needs to be updated

## Proposed changes: 
diff --git a/deployment/deployment-template.yaml b/deployment/deployment-template.yaml
-apiVersion: apps/v1beta2
+apiVersion: apps/v1

**Comment by rusenask** [comment]
thanks, fixed!
