### ISSUE TITLE
crashes with tunnel and GCP credentials

### ISSUE THREAD

**Issue by vinfry** [keel-hq/keel#501]
Hi,

I am trying to use keel with webhookrelay tunnel, in order to accomplish this i had to modify deployment:
`command: ["/relayd", "--mode", "tunnel", "--tunnels", "$MY_TUNNEL"]`
This was taken from [https://github.com/keel-hq/keel/blob/master/deployment/deployment-template.yaml#L129](url)
Since i have a few projects, i need to use googleApplicationCredentials, the full command is:
`helm install -n keel ./ --namespace=kube-system --set gcr.enabled='true' --set gcr.projectId=$MY_PROJECT --set gcr.pubsub.enabled='true' --set notificationLevel='debug' --set gcr.clusterName=$MY_CLUSTER --set googleApplicationCredentials=$MY_BASE64_KEY --set debug='true' --set webhookRelay.enabled='true' --set webhookRelay.secret=$WEBHOOK_SECRET --set webhookRelay.key=$WEBHOOK_KEY --set basicauth.enabled='true' --set basicauth.user=$KEEL_USER --set basicauth.password=$KEEL_PASSWORD`

Unfortunately, keel fails with the following:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1556a85]

goroutine 43 [running]:
github.com/keel-hq/keel/trigger/poll.(*RepositoryWatcher).addJob(0xc0006beae0, 0xc000a11170, 0xc0008365f0, 0x9, 0x31d3a60, 0xc000881a00)
        /go/src/github.com/keel-hq/keel/trigger/poll/watcher.go:234 +0x255
github.com/keel-hq/keel/trigger/poll.(*RepositoryWatcher).watch(0xc0006beae0, 0xc000a11170, 0x0, 0x0, 0x7000103, 0x0)
        /go/src/github.com/keel-hq/keel/trigger/poll/watcher.go:192 +0x8de
github.com/keel-hq/keel/trigger/poll.(*RepositoryWatcher).Watch(0xc0006beae0, 0xc000aba670, 0x2, 0x2, 0x0, 0x0)
        /go/src/github.com/keel-hq/keel/trigger/poll/watcher.go:134 +0xf2
github.com/keel-hq/keel/trigger/poll.(*DefaultManager).scan(0xc0006e9540, 0x208da60, 0xc00034c700, 0x1, 0x1)
        /go/src/github.com/keel-hq/keel/trigger/poll/manager.go:79 +0x78
github.com/keel-hq/keel/trigger/poll.(*DefaultManager).Start(0xc0006e9540, 0x208da60, 0xc00034c700, 0x0, 0x0)
        /go/src/github.com/keel-hq/keel/trigger/poll/manager.go:48 +0xf2
created by main.setupTriggers
        /go/src/github.com/keel-hq/keel/cmd/keel/main.go:436 +0x6ed

The same setup was working fine a few months ago. So the questions are:

1. Will you support tunnels for webhookrelay?
2. Is that a bug or you have some workaround?

**Comment by rusenask** [comment]
Hi, this does look an issue with the image polling part, not the tunnels. I will have a look :)

**Comment by vinfry** [comment]
> 
> 
> Hi, this does look an issue with the image polling part, not the tunnels. I will have a look :)

thanks, looking for your update
