### ISSUE TITLE
Harbor webhook trigger payload changed?

### ISSUE THREAD

**Issue by immanuelfodor** [keel-hq/keel#510]
Hi Everyone,

I spent the whole afternoon trying to get the Harbor webhook trigger work without success, maybe Keel only supports the v1.X.X notification format and not the new v2.0.X? (If there is any difference, I only tried with v2.) Or did I miss something somewhere?

According to https://keel.sh/docs/#harbor-webhooks I added a new webhook for image push in Harbor v2 to https://example.com/v1/webhooks/registry

![image](https://user-images.githubusercontent.com/21174107/85205034-c988e380-b318-11ea-8394-4f2aa732d733.png)

But no matter how I try to configure Keel, it seems that the webhook is rejected or discarded silently. According to the Harbor jobservice logs, the webhook is pulled successfully but there is no sign of it in the Keel logs/audit menu. I also added another webhook in Harbor to check the payload, and if I send it with curl to Keel, it's the same, no log of the trigger but the response code is 200 OK. However, if I send random data to Keel, there is a trigger error logged and I get back code 400, so it must accept the JSON. I also tried setting the AUTHENTICATED_WEBHOOKS env variable to true and providing the user:pass string in base64 encoded format to Harbor auth header option with and without Basic prefix (i.e. Basic asdasdasd or just asdasdasd in the form field), it doesn't change, the trigger seems to be swallowed. On the other hand, polling works fine, setting it to 1m solves it mainly, it just produces thousands of pulls in the Harbor pull counter.

If the Harbor payload has changed, could you please fix it? If I misconfigured something somewhere, could you please provide better docs for enabling Harbor webhooks? For example, the AUTHENTICATED_WEBHOOKS env var is only mentioned once without much explanation, maybe it has to do something with it? When experimenting with curl, I also saw that I got back 200 OK for posting the Harbor push notification payload no matter if I set the authorization header or not when the auth webhook var was true. Maybe it's completely unrelated. I feel lost with enabling the Harbor webhook trigger, please help.

**Comment by rusenask** [comment]
Hi, could you provide an example of the webhook that your instance Harbor posts? I can check the format

**Comment by immanuelfodor** [comment]
Of course, it's the following:

```json
{
  "type": "PUSH_ARTIFACT",
  "occur_at": 1592659997,
  "operator": "robot$ci-user",
  "event_data": {
    "resources": [
      {
        "digest": "sha256:ff11b0b5aaab2432d17b143ecbe08202ea7f6ca3839253874ed9b0acc345a879",
        "tag": "latest",
        "resource_url": "example.com/repo/imagename:latest"
      }
    ],
    "repository": {
      "date_created": 1592200834,
      "name": "imagename",
      "namespace": "repo",
      "repo_full_name": "repo/imagename",
      "repo_type": "private"
    }
  }
}
```
```bash
# with auth header (user:name as base64)
curl -v -X POST -d '{"type": "PUSH_ARTIFACT", "occur_at": 1592659997, "operator": "robot$ci-user", "event_data": {"resources": [{"digest": "sha256:ff11b0b5aaab2432d17b143ecbe08202ea7f6ca3839253874ed9b0acc345a879", "tag": "latest", "resource_url": "example.com/repo/imagename:latest"}], "repository": {"date_created": 1592200834, "name": "imagename", "namespace": "repo", "repo_full_name": "repo/imagename", "repo_type": "private"}}}' -H "Content-Type: application/json" -H "Authorization: Basic asdasdasdasd" https://keel.example.com/v1/webhooks/registry

# without auth header
curl -v -X POST -d '{"type": "PUSH_ARTIFACT", "occur_at": 1592659997, "operator": "robot$ci-user", "event_data": {"resources": [{"digest": "sha256:ff11b0b5aaab2432d17b143ecbe08202ea7f6ca3839253874ed9b0acc345a879", "tag": "latest", "resource_url": "example.com/repo/imagename:latest"}], "repository": {"date_created": 1592200834, "name": "imagename", "namespace": "repo", "repo_full_name": "repo/imagename", "repo_type": "private"}}}' -H "Content-Type: application/json" https://keel.example.com/v1/webhooks/registry
```

**Comment by rusenask** [comment]
Hi, try sending webhooks to `/v1/webhooks/harbor`, let me know if it works

**Comment by immanuelfodor** [comment]
Do I need to update Keel or do anything else to get the change, or this path is built-in from the start? I modified the webhook from registry to harbor but nothing seems to be changed. When a new image gets pushed, other Harbor webhooks send notifications as always, this one in Harbor logs is also successful but nothing is logged in Keel pod log, nothing in Keel audit log, and Keel also doesn't emit a Mattermost update notification. The webhook auth env is false by the way.

**Comment by rusenask** [comment]
yeah it was there for a while, which version of keel are you running?

**Comment by immanuelfodor** [comment]
keel --version said nothing useful in the pod but kubectl describe has this on the pod: 

Image ID:      docker-pullable://keelhq/keel@sha256:2d023b4328403aeac05607e91f3dc9a6f752043bced5b66e7b05f0bec8f436dd

The deployment is keelhq/keel:latest

**Comment by qroccia** [comment]
Hello,
Same issue with keel:latest (Digest:sha256:0dd122865f4228756c5fbee48155b11758484180dba9700a7936b54cc9f510d5) and harbor (v2.0.1-d714b3ea)

I tried on the following endpoints : /v1/webhooks/harbor
Return code is 200 but it doesn't trigger anything nor create entry in logs.

**Comment by immanuelfodor** [comment]
My short term solution was to use an extra CI deploy step wish sends a small payload to Keel's `/v1/webhooks/native` until this one is fixed to allow Harbor to send the notification when the image is processed. The native JSON looks like: `{ "name": "harbor.hostname.tld/project/image", "tag": "tagname" }`

**Comment by NULLx76** [comment]
I am encountering the same issue, if I turn on debug logging I do get a log entry:
```
time="2020-09-23T18:34:33Z" level=debug msg="harborHandler: received event, looking for a pushImage tag" event="{PUSH_ARTIFACT 1600886072 admin {[{sha256:<hash> latest harbor.example.tld/library/hello-world:latest}] {1600856656 hello-world library library/hello-world public}}}"

But it doesn't trigger an update.

**Comment by NULLx76** [comment]
I had a quick look at the code and the problem seems to lie here:
https://github.com/keel-hq/keel/blob/3c3c23da3c790215e1b015227fc5bb65a33ecdc1/pkg/http/harbor_webhook_trigger.go#L84
The previous version probably had `pushImage` but now it's `PUSH_ARTIFACT`.  It doesn't seem like anything else has changed so maybe the fix can be as easy as changing
```go
if hn.Type == "pushImage" { 
```
to
```go
if hn.Type == "pushImage" || hn.Type == "PUSH_ARTIFACT" { 
```

**Comment by immanuelfodor** [comment]
Woow, thanks @NULLx76, I'm waiting for the new release to test this.

**Comment by shinebayar-g** [comment]
Hi. AFAIK keel's current endpoint `/v1/webhooks/registry` only supports harbor's system notification webhooks that are configured in harbor's `common/config/registry/config.yml` file (which is useless as of harbor's new webhook settings feature introduced). Looks like you're trying to use harbor's new webhook settings introduced in quite a recent version 1.9 or 1.8, which is configurable in its UI like this?
![image](https://user-images.githubusercontent.com/3091558/94097462-25697980-fdec-11ea-9f52-a8c2203f339f.png)

Did you try the new endpoint `/v1/webhooks/harbor`? I couldn't test it since I'm stuck on old harbor version.

Looks like new webhooks also support authentication header. 
If [admin dashboard](https://keel.sh/docs/#enabling-admin-dashboard) is enabled, does it also protects keel's webhook endpoints as well @rusenask ? If so, does that mean we can actually enable admin dashboard to protect endpoints from blind webhook payloads like mentioned [here](https://github.com/keel-hq/keel/issues/347#issuecomment-502036154)?

**Comment by immanuelfodor** [comment]
I haven't got the chance to test it again (previously it didn't work, hence I opened this issue), I'm waiting for the next release to try the above fix for webhooks sent directly from Harbor and remove the hotfix webhook pull from the CI. I'm using Harbor 2.X and the webhook page is not like yours. Here I have a table where I can add multiple webhooks and here is the add webhook popup: 

![Screenshot_20200924-062046](https://user-images.githubusercontent.com/21174107/94100542-3804a280-fe2e-11ea-96f1-97a5a6977c2c.jpg)

**Comment by shinebayar-g** [comment]
Ah that looks nice. Yeah I'm on old version. Maybe webhook was just introduced or something ..

One thing I'm actively looking for is webhook authentication. Currently keel updates our images based on whatever thrown at them.

**Comment by immanuelfodor** [comment]
Maybe you could try adding a reverse proxy in front of Keel, and set up HTTP Basic auth there, then try adding https://username:password@keel.examle.com/.... as webhook URL. It's just an idea, I don't know if Harbor accepts such URLs.

**Comment by rusenask** [comment]
> Ah that looks nice. Yeah I'm on old version. Maybe webhook was just introduced or something ..
> 
> > I'm waiting for the next release to try the above fix for webhooks sent directly from Harbor and remove the hotfix webhook pull from the CI.
> 
> That makes sense, thank you.
> 
> One thing I'm actively looking for is webhook authentication. Currently keel updates our images based on whatever thrown at them.

If you set env variable `AUTHENTICATED_WEBHOOKS=true` then all webhook endpoints will require authentication

**Comment by immanuelfodor** [comment]
From the opening post: 

> I also tried setting the AUTHENTICATED_WEBHOOKS env variable to true and providing the user:pass string in base64 encoded format to Harbor auth header option with and without Basic prefix (i.e. Basic asdasdasd or just asdasdasd in the form field), it doesn't change, the trigger seems to be swallowed. 

But I think it was swallowed by the wrong internal working of the endpoint, not becuase auth was not working, I just wanted to clarify.

**Comment by NULLx76** [comment]
@shinebayar-g are you sure you are running an up to date version of keel as that is [the exact error](https://github.com/keel-hq/keel/issues/510#issuecomment-697863946) I had before submitting the PR

**Comment by shinebayar-g** [comment]
Ah crap, I'm such a rookie. I'm on 0.16.1. So should I run `:latest` then?

**Comment by NULLx76** [comment]
Ah, I didn't realise that there hasn't been a release since my fix. But yes using `:latest` should work then, not sure if it is considered unstable but it has been working fine for me so far.

**Comment by shinebayar-g** [comment]
It's working nice!

**Comment by immanuelfodor** [comment]
I'm using native webhooks from the CI pipeline as a workaround until Harbor hooks available outside the latest tag. I try to avoid the latest tag as much as possible, so I'm still on 0.17.0-rc1. Keel manages itself, too, so a new (rc) release would be great 😃

**Comment by shinebayar-g** [comment]
I noticed there are some additional error / warning logs introduced on latest tag :/
Probably not so stable as 0.16.1.

**Comment by ElArtista** [comment]
Got bitten by this too, awaiting new release! Changed:
```
image:
  tag: latest
```
in my values.yaml for the helm chart and everything works nicely now!
