### ISSUE TITLE
deployment-rbac-whr-sidecar.yaml is broken

### ISSUE THREAD

**Issue by Fogapod** [keel-hq/keel#511]
Hello, I tried following the guide for setting up keel with relay webhooks and had troubles making the deployment work.
There are multiple issues:
```sh
kubectl apply -f deployment-rbac-whr-sidecar.yaml
namespace/keel created
poddisruptionbudget.policy/keel created error: error validating "deployment-rbac-whr-sidecar.yaml": error validating data: [unknown object type "nil" in Secret.data.BASIC_AUTH_PASSWORD, unknown object type "nil" in Secret.data.HIPCHAT_APPROVALS_PASSWORT, unknown object type "nil" in Secret.data.HIPCHAT_TOKEN, unknown object type "nil" in Secret.data.SLACK_TOKEN]; if you choose to ignore these errors, turn validation off with --validate=false
```

After removing/filling these fields with `""` new issues appear:
```sh
kubectl apply -f deployment-rbac-whr-sidecar.yaml
namespace/keel unchanged
poddisruptionbudget.policy/keel unchanged
secret/keel created
serviceaccount/keel created
clusterrole.rbac.authorization.k8s.io/keel created
clusterrolebinding.rbac.authorization.k8s.io/keel created
service/keel created
error validating "deployment-rbac-whr-sidecar.yaml": error validating data: ValidationError(Deployment.spec.template.spec.containers[0].env[6].valueFrom.secretKeyRef): missing required field "key" in io.k8s.api.core.v1.SecretKeySelector; if you choose to ignore these errors, turn validation off with --validate=false
Error from server (Invalid): error when creating "deployment-rbac-whr-sidecar.yaml": PersistentVolumeClaim "keel" is invalid: spec.storageClassName: Invalid value: "-": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```

Then:
```sh
kubectl delete -f deployment-rbac-whr-sidecar.yaml
namespace/keel unchanged
poddisruptionbudget.policy/keel unchanged
secret/keel created
serviceaccount/keel created
clusterrole.rbac.authorization.k8s.io/keel created
clusterrolebinding.rbac.authorization.k8s.io/keel created
service/keel created
unable to recognize "deployment-rbac-whr-sidecar.yaml": no matches for kind "ManagedCertificate" in version "networking.gke.io/v1beta1"
```
Even after resolving everything, half of the deployment is in error state and I did not dig further.
Looks like https://github.com/keel-hq/keel/commit/7472bcf8bb34bb35addaf5b7230fd74fa0f4ae55#diff-5d084b6aa65ade0e7be3bcda074a2ada broke everything. Previous commit works fine with minor changes (`apps/v1beta2` => `apps/v1` and `keel-webhookrelay` => `webhookrelay-credentials`).

Either article https://keel.sh/examples/#configure-dockerhub-code-repository-webhook should be updated explaining how to use the new config version as it requires big changes and doesnt work out of the box or changes should be reversed.

**Comment by rusenask** [comment]
Hi, thanks, looking into it!

**Comment by rusenask** [comment]
Hi, updated docs to use the newly release webhook relay operator: https://keel.sh/examples/#example-1-push-to-deploy. 

At this point it's just easier to use Helm to configure things. Also, with the operator it will be configuring things for you and you can keep configuration in a CR.

If you prefer, sidecar then helm chart can also automatically create a sidecar for you.
