### ISSUE TITLE
x509: certificate is valid for *, not xx.xx.com"

### ISSUE THREAD

**Issue by rreilly-edr** [keel-hq/keel#526]
Trying to setup an email notification, this is a standard smtp, i can send email using telnet. is this error coming from keel or is it passing it back from the smtp server ?

```
time="2020-07-22T15:02:20Z" level=error msg="extension.notification.mail: failed to send notification" error="x509: certificate is valid for *, not xx.xx.com"
```

**Comment by rusenask** [comment]
does the server have a valid TLS certificate?
