### ISSUE TITLE
metadata.labels: Invalid value: "glob:dev-*": a valid label must be an empty string or consist of alphanumeric characters

### ISSUE THREAD

**Issue by cmoone** [keel-hq/keel#537]
I'm attempting to use  keel.sh/policy: "glob:dev-*" to match those versions prepended with dev. This fails validation every time. keel.sh/policy: "regexp:^dev" fails with the same error message. How can I pass template validation with either of these methods?

**Comment by rusenask** [comment]
Hi,
Set it in annotations instead of labels, it consumes the same way.

**Comment by cmoone** [comment]
Thanks, worked like a charm.
