### ISSUE TITLE
No option to send notifications to MS Teams

### ISSUE THREAD

**Issue by mrsegen** [keel-hq/keel#539]
As [discussed](https://kubernetes.slack.com/archives/C6JDWE7M2/p1599144357003700) in the kuberenetes > #keel slack channel, it does not seem as though Keel's generic webhook is compatible with MS Teams's [Connectors paradigm](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using).

I plan to work on a PR towards this, starting [here](https://github.com/keel-hq/keel/blob/master/extension/notification/webhook/webhook.go#L32).

**Comment by rusenask** [comment]
Excellent, thank you!
