### ISSUE TITLE
GCR 401 Unauthorized

### ISSUE THREAD

**Issue by Harrisonl** [keel-hq/keel#546]
Hey i have followed all the steps in the getting started guide but I am getting a 401 when trying to set up polling with GCR, I know there is the pubsub adapter as well but for now I am happy with just going with polling every minute. The error I get is:

```
Get \"https://gcr.io/v2/<MY IMAGE>/manifests/latest\": http: non-successful response (status=401 body=\"{\\\"errors\\\":[{\\\"code\\\":\\\"UNAUTHORIZED\\\",\\\"message\\\":\\\"You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication\\\"}]}\")" image="<MY IMAGE>" password= username=
```

This is installed via the kubernetes manifest on a private GKE cluster, using `latest` tag - let me know if there is any more information you need! I might be missing something very obviou

**Comment by rusenask** [comment]
Hi,
Have you mounted gcp credentials?

**Comment by Harrisonl** [comment]
hey @rusenask  thanks for the quick reply! That might be the issue - do you have a link to the docs for how to mount it (/ what credentials to mount?) I can only see these ones here https://keel.sh/docs/#google-cloud-gcr-registry but from the looks of it this is only for the pubsub side of things

**Comment by rusenask** [comment]
hi @Harrisonl , yeah, GCP credentials work the same, the support for gcr polling was added here https://github.com/keel-hq/keel/pull/424. 

So you need to do few things:
1. Create a service account with probably Storage Viewer permissions (might be different, need to check which perms allow accessing GCR)
2. Create a secret with the service credentials json
3. Mount it to Keel's deployment
4. Specify the mount path with env variable GOOGLE_APPLICATION_CREDENTIALS

If you are installing Keel through Helm, specify this value https://github.com/keel-hq/keel/blob/master/chart/keel/values.yaml#L180:

```
--set googleApplicationCredentials=$(cat <JSON_KEY_FILE> | base64)
```

**Comment by Harrisonl** [comment]
@rusenask that worked perfectly!
