### ISSUE TITLE
Policies with regular expression with column chars not supported

### ISSUE THREAD

**Issue by maxgio92** [keel-hq/keel#596]
Hi,
it seems that regular expressions that contain column characters are not accepted, like this one:

```
^(?:[^l\n]|l(?:$|[^a\n]|a(?:$|[^t\n]|t(?:$|[^e\n]|e(?:$|[^s\n]|s(?:$|[^t\n])))))).*$
```

of which an example code [here](https://play.golang.org/p/YSBz1D8oy3r).

that should match everything but `latest`.

This isn't accepted as the count of column characters in the policy string are expected to be exactly one, as for `NewRegexpPolicy()` in [`internal/policy/regexp.go`](https://github.com/keel-hq/keel/blob/master/internal/policy/regexp.go):

```
func NewRegexpPolicy(policy string) (*RegexpPolicy, error) {
        if strings.Contains(policy, ":") {
                parts := strings.Split(policy, ":")
                if len(parts) == 2 {

                        rx, err := regexp.Compile(parts[1])
                        if err != nil {
                                return nil, fmt.Errorf("failed to parse regexp pattern, error: %s", err)
                        }

                        return &RegexpPolicy{
                                regexp: rx,
                                policy: policy,
                        }, nil
                }
        }

        return nil, fmt.Errorf("invalid regexp policy: %s", policy)
}
```

but this syntax should be [RE2](https://github.com/google/re2/wiki/Syntax) compatible - as in turn supported by [`regexp`](https://golang.org/pkg/regexp/)

Am I missing something in your opinion?

Thanks

**Comment by rusenask** [comment]
you are right, `   parts := strings.Split(policy, ":")` should be using strings.SplitN function (https://golang.org/pkg/strings/#SplitN), could you please try patching it?

**Comment by maxgio92** [comment]
Sure @rusenask ! Thanks for the super-rapid response :)

**Comment by maxgio92** [comment]
Hi @rusenask when you want I opened #597 :)
