### ISSUE TITLE
Keel fails to upgrade helm release with helm v3 because of ClusterRole restrictions

### ISSUE THREAD

**Issue by neurosis71** [keel-hq/keel#603]
Hi guys,

I bumped into an issue where keel fails to upgrade my helm chart due to the Keel role that doesn't have sufficient rights.

here are the kind of logs I get from the keel pod :

```
level=info msg="warning: Upgrade \"manager-testing\" failed: could not get information about the resource: services \"manager-testing-eazen-manager-service\" is forbidden: User \"system:serviceaccount:monitor:keel\" cannot get resource \"services\" in API group \"\" in the namespace \"testing\""
time="2021-04-26T17:17:01Z" level=fatal msg="helm3: failed to update release from chart" error="could not get information about the resource: services \"manager-testing-eazen-manager-service\" is forbidden: User \"system:serviceaccount:monitor:keel\" cannot get resource \"services\" in API group \"\" in the namespace \"testing\""
```

I played with keel's cluster role to see what kind of resources was involved :

- secrets get
- networkpolicies create|upgrade
- services get

For information the helm chart I'm trying to upgrade is a in house chart with no secrets or networkpolicies.
When I modify the cluster role to give all right on all namespaces to all resources everything works fine.
I don't fully understand the implications of opening the role rights like this and why keel encounters this errors since my chart doesn't have the impacted resources (except for a service).

I installed keel via helm. provider helmv3, kubernetes 1.19

Am I missing something here ?

Thanks for the help guys !

**Comment by mbeliaevsetro** [comment]
Also bumped into role restrictions. In my case, this role allows keel to do the magic
`name: keel
  resourceVersion: "3333763"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterroles/keel
  uid: 1cc6dcc5-be60-4828-b3f4-73fa6f42a16a
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - watch
  - list
- apiGroups:
  - ""
  resources:
  - secrets
  - services
  verbs:
  - get
  - watch
  - list
  - create
  - update
- apiGroups:
  - ""
  - extensions
  - apps
  - batch
  resources:
  - pods
  - replicasets
  - replicationcontrollers
  - statefulsets
  - deployments
  - daemonsets
  - jobs
  - cronjobs
  verbs:
  - get
  - delete
  - watch
  - list
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  - pods/portforward
  verbs:
  - get
  - create
  - update`
 
 Team, is there any relevant PR for this?

**Comment by djschaap** [comment]
This looks related to what I reported in #599 .  I would like to see ClusterRole/keel be granted significantly more permissions by default (it used to be more-or-less cluster-admin, I believe).

**Comment by joebowbeer** [comment]
Close?
