### ISSUE TITLE
Unable to use authentication on native webhook

### ISSUE THREAD

**Issue by lehno** [keel-hq/keel#620]
I did not find any docs, but I saw in the code that if you have an ENVVAR called AUTHENTICATED_WEBHOOKS, the caller must pass the user and password to trigger it. No lucky here.

Any ideas?

**Comment by diegorcunha** [comment]
Yes, I have the same problem, I need to enable the webhook to ask for authentication, but when I pass the ENV VAR AUTHENTICATED WEBHOOKS=true nothing happens...

**Comment by rusenask** [comment]
hey, do you also set `BASIC_AUTH_USER` and `BASIC_AUTH_PASSWORD` variables?

**Comment by diegorcunha** [comment]
Yes, both are set, and the authentication on the UI is working, but in the webhook, if I tried with or without login and password I receive the request in the UI in the same way

**Comment by lehno** [comment]
I set the BASIC_AUTH_USER and BASIC_AUTH_PASSWORD as well, the UI works great, but the webhook does not ask for it
