### ISSUE TITLE
Problem with AWS_ROLE_ARN

### ISSUE THREAD

**Issue by TheChickenDevOps** [keel-hq/keel#669]
Hello,

If I set the deployment to work via AWS_ROLE_ARN, then not pass it ACCESS and SECRET, it doesn't work.
I am deploying Keel via Helm.. version helm 0.9.10 with Keel version 0.16.1

**ERROR**:
_NoCredentialProviders: no valid providers in chain. Deprecated. Keel_

But if I go through the deployment secret and access it works fine.
What could I have done wrong?

I follow this guide: https://keel.sh/docs/#polling-with-aws-ecr

**Comment by joebowbeer** [comment]
What permissions does the associated IAM role have?

For cross-account access to ECR you need latest image with this fix:

https://github.com/keel-hq/keel/pull/569

**Comment by TheChickenDevOps** [comment]
I use 0.16.1 version of Keel, what do u use?

**Comment by TheChickenDevOps** [comment]
> What permissions does the associated IAM role have?
> 
> For cross-account access to ECR you need latest image with this fix:
> 
> #569
> 
> I'm not using helm and it's working for me, so you might want to eliminate helm from the equation (`helm template`)

I use 0.16.1 version of Keel, what do u use?

**Comment by joebowbeer** [comment]
> I use 0.16.1 version of Keel, what do u use?

latest

I rendered the helm chart and changed the image tag to pick up the most recently published version

**Comment by joebowbeerxealth** [comment]
What permissions does the IAM role associated with the keel service account have?

**Comment by joebowbeer** [comment]
What permissions does the IAM role associated with the keel service account have?

**Comment by TheChickenDevOps** [comment]
I've fix this error, the role associated with keel service account has "Administrator" permission for the moment.

`time="2022-07-28T07:29:15Z" level=error msg="provider.defaultProviders: failed to get tracked images" error="context deadline exceeded" provider=helm
time="2022-07-28T07:29:20Z" level=error msg="provider.defaultProviders: failed to get tracked images" error="context deadline exceeded" provider=helm`

With :latest i've this error now.
