### ISSUE TITLE
Feature request: deploying Kubernetes StatefulSets

### ISSUE THREAD

**Issue by praseodym** [keel-hq/keel#68]
In Kubernetes 1.7, StatefulSets support rolling updates just like Deployments. It would be great if we could use keel to update StatefulSets as well.

**Comment by rusenask** [comment]
This is definitely a wanted feature, however it will require some redesigning of the k8s provider as it would be nice to support different kinds of workloads as well - daemonset, petset. 

Are you currently using StatefulSets?

**Comment by praseodym** [comment]
Yes, we're using StatefulSets for applications that require persistent storage (e.g. databases). There's no proper way to do that with Deployments.

**Comment by jaredallard** [comment]
Any plans to support this?

**Comment by rusenask** [comment]
Hi guys, so the PR is merged and release candidate is available. I have tested both statefulset and daemonset updates. If you find any problems, please create separate issues :)
