### ISSUE TITLE
 *v1beta1.CronJob: the server could not find the requested resource

### ISSUE THREAD

**Issue by unixbird** [keel-hq/keel#727]
Updated k3s to 1.26.x and found that the cronjob resources need to be updated. 

Full error:
E0607 03:05:46.600805       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.1-0.20190516230509-ae8359b20417+incompatible/tools/cache/reflector.go:94: Failed to list *v1beta1.CronJob: the server could not find the requested resource

**Comment by chrisbolt** [comment]
Appears to be fixed by #706 which is included in version 0.18.0.

**Comment by unixbird** [comment]
Tested and it now works on 1.26.x! Thank you!
