### ISSUE TITLE
Can keel  handle multiple containers in a pod deployment?

### ISSUE THREAD

**Issue by zestysoft** [keel-hq/keel#748]
I've got some pods that have multiple containers -- some that are part of init, and some that run concurrently.  I think all of the keel settings happen at the root of the deployment, so I'm uncertain how to, say, assign glob policies per container?

**Comment by joebowbeer** [comment]
keel can watch containers and initContainers (#734)

**Comment by joebowbeer** [comment]
Annotations are per pod controller AFAIK. I don't know of a way to separate by container.

**Comment by david-garcia-garcia** [comment]
By default it uses the same watch config for all containers. There is a new yet undocumented annotation to at least decide which containers should be monitored: https://github.com/keel-hq/keel/commit/10acf529191bc127feb65873f2d2f7fa77a0a52f

But if you want to watch more than one container per K8S object, they will all share policy, interval, etc.
