### ISSUE TITLE
keel is using deprecated api /apis/batch/v1beta1/cronjobs

### ISSUE THREAD

**Issue by sreenivas-ps** [keel-hq/keel#752]
I'm using GKE and being alerted that keel is using deprecated /apis/batch/v1beta1/cronjobs api.
currently using chart version: `0.9.11`,  appversion:  `0.16.1`. 

In the code I'm seeing that it is updated: https://github.com/keel-hq/keel/blob/master/internal/k8s/watcher.go#L11-L12.
Can you please confirm if this fixed in the current chart version 1.0.3 (app version: 0.19.1) ?

Thanks.

**Comment by david-garcia-garcia** [comment]
Fixed on latest release.
